#!/usr/bin/env bash
# Linux/macOS counterpart to Get-Railway-Variables.ps1
set -euo pipefail

USERNAME="${1:-demo}"
PASSWORD="${2:-}"
FRONTEND_ORIGIN="${3:-}"

if [[ -z "$PASSWORD" ]]; then
  PASSWORD="$(python3 -c "import secrets; print(secrets.token_urlsafe(18))")"
fi

JWT_SECRET="$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")"

declare -A VARIABLES=(
  [ENVIRONMENT]=production
  [BACKEND_HOST]=0.0.0.0
  [SERVE_FRONTEND_DIST]=1
  [FRONTEND_DIST_DIR]=frontend/dist
  [USE_GPU]=0
  [WHISPER_DEVICE]=cpu
  [WHISPER_COMPUTE_TYPE]=int8
  [WHISPER_MODEL_SIZE]=tiny
  [WHISPER_CPU_THREADS]=4
  [WHISPER_NUM_WORKERS]=1
  [PRELOAD_MODELS]=1
  [TRANSLATION_DEVICE]=cpu
  [GPU_COST_MODE]=low
  [STT_MAX_CONCURRENCY]=2
  [WHISPER_BEAM_SIZE]=1
  [VAD_RECENT_CHUNKS]=2
  [VAD_SILENT_CHECKS]=1
  [VAD_FORCE_FINAL_SECONDS]=0.35
  [SPEECH_MERGE_MS]=80
  [MIN_SPEECH_BYTES]=4000
  [NEAR_ZERO_LATENCY_MODE]=1
  [PARTIAL_STT_MIN_BYTES]=4000
  [PARTIAL_STT_INTERVAL_MS]=250
  [PIPELINE_STEP_TIMEOUT_SECONDS]=10
  [TTS_CHUNK_CHARS]=26
  [TRANSLATION_BACKEND]=marian
  [HYBRID_ENABLE_MARIAN_FALLBACK]=1
  [HYBRID_ENABLE_REMOTE]=0
  [PREFER_CLOUD_TTS]=0
  [STT_PROVIDER]=local
  [REQUESTS_PER_MINUTE]=120
  [QUOTA_REQUESTS_PER_HOUR]=500
  [MAX_ACTIVE_STREAMS_PER_USER]=5
  [JWT_SECRET]="$JWT_SECRET"
  [USERS]="${USERNAME}:${PASSWORD}"
  [USER_TIERS]="${USERNAME}:free"
)

if [[ -n "$FRONTEND_ORIGIN" ]]; then
  VARIABLES[ALLOWED_ORIGINS]="$FRONTEND_ORIGIN"
fi

ORDER=(
  ENVIRONMENT BACKEND_HOST SERVE_FRONTEND_DIST FRONTEND_DIST_DIR USE_GPU
  WHISPER_DEVICE WHISPER_COMPUTE_TYPE WHISPER_MODEL_SIZE WHISPER_CPU_THREADS
  WHISPER_NUM_WORKERS PRELOAD_MODELS TRANSLATION_DEVICE GPU_COST_MODE
  STT_MAX_CONCURRENCY WHISPER_BEAM_SIZE VAD_RECENT_CHUNKS VAD_SILENT_CHECKS
  VAD_FORCE_FINAL_SECONDS SPEECH_MERGE_MS MIN_SPEECH_BYTES NEAR_ZERO_LATENCY_MODE
  PARTIAL_STT_MIN_BYTES PARTIAL_STT_INTERVAL_MS PIPELINE_STEP_TIMEOUT_SECONDS
  TTS_CHUNK_CHARS TRANSLATION_BACKEND HYBRID_ENABLE_MARIAN_FALLBACK
  HYBRID_ENABLE_REMOTE PREFER_CLOUD_TTS STT_PROVIDER REQUESTS_PER_MINUTE
  QUOTA_REQUESTS_PER_HOUR MAX_ACTIVE_STREAMS_PER_USER JWT_SECRET USERS USER_TIERS
)

echo ""
echo "Paste these into Railway service variables:"
echo ""
for key in "${ORDER[@]}"; do
  echo "${key}=${VARIABLES[$key]}"
done
if [[ -n "$FRONTEND_ORIGIN" ]]; then
  echo "ALLOWED_ORIGINS=${FRONTEND_ORIGIN}"
fi
echo ""
echo "Login for the app:"
echo "  username: $USERNAME"
echo "  password: $PASSWORD"
echo ""
echo "Keep the password and JWT_SECRET private."
