"""Verified-style high-stakes EN<->HT glossary entries (expand with native review)."""

HT_HIGH_STAKES_GLOSSARY: list[dict[str, str]] = [
    {"source": "I need a doctor", "target": "Mwen bezwen yon doktè", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen bezwen yon doktè", "target": "I need a doctor", "lang_pair": "ht-en", "context": "medical"},
    {"source": "Call an ambulance", "target": "Rele yon anbilans", "lang_pair": "en-ht", "context": "emergency"},
    {"source": "Rele yon anbilans", "target": "Call an ambulance", "lang_pair": "ht-en", "context": "emergency"},
    {"source": "Where is the hospital", "target": "Kote lopital la", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Kote lopital la", "target": "Where is the hospital", "lang_pair": "ht-en", "context": "medical"},
    {"source": "Where is the nearest hospital", "target": "Kote lopital ki pi pre a ye", "lang_pair": "en-ht", "context": "medical"},
    {"source": "I feel sick", "target": "Mwen pa santi m byen", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen pa santi m byen", "target": "I feel sick", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I have a fever", "target": "Mwen gen lafyèv", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen gen lafyèv", "target": "I have a fever", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I have chest pain", "target": "Mwen gen doulè nan pwatrin", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen gen doulè nan pwatrin", "target": "I have chest pain", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I am allergic", "target": "Mwen gen alèji", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen gen alèji", "target": "I am allergic", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I am pregnant", "target": "Mwen ansent", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen ansent", "target": "I am pregnant", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I cannot breathe", "target": "Mwen pa ka respire", "lang_pair": "en-ht", "context": "emergency"},
    {"source": "Mwen pa ka respire", "target": "I cannot breathe", "lang_pair": "ht-en", "context": "emergency"},
    {"source": "Help me", "target": "Ede m", "lang_pair": "en-ht", "context": "emergency"},
    {"source": "Ede m", "target": "Help me", "lang_pair": "ht-en", "context": "emergency"},
    {"source": "Call the police", "target": "Rele lapolis", "lang_pair": "en-ht", "context": "emergency"},
    {"source": "Rele lapolis", "target": "Call the police", "lang_pair": "ht-en", "context": "emergency"},
    {"source": "I do not understand", "target": "Mwen pa konprann", "lang_pair": "en-ht", "context": "general"},
    {"source": "Mwen pa konprann", "target": "I do not understand", "lang_pair": "ht-en", "context": "general"},
    {"source": "Please speak slowly", "target": "Tanpri pale dousman", "lang_pair": "en-ht", "context": "general"},
    {"source": "Tanpri pale dousman", "target": "Please speak slowly", "lang_pair": "ht-en", "context": "general"},
    {"source": "I need medicine", "target": "Mwen bezwen medikaman", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen bezwen medikaman", "target": "I need medicine", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I am in pain", "target": "Mwen gen doulè", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen gen doulè", "target": "I am in pain", "lang_pair": "ht-en", "context": "medical"},
    {"source": "My child is sick", "target": "Pitit mwen malad", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Pitit mwen malad", "target": "My child is sick", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I need a interpreter", "target": "Mwen bezwen yon entèprèt", "lang_pair": "en-ht", "context": "general"},
    {"source": "Mwen bezwen yon entèprèt", "target": "I need an interpreter", "lang_pair": "ht-en", "context": "general"},
    {"source": "Where is the bathroom", "target": "Kote twalèt la", "lang_pair": "en-ht", "context": "travel"},
    {"source": "Kote twalèt la", "target": "Where is the bathroom", "lang_pair": "ht-en", "context": "travel"},
    {"source": "I lost my passport", "target": "Mwen pèdi paspò mwen", "lang_pair": "en-ht", "context": "travel"},
    {"source": "Mwen pèdi paspò mwen", "target": "I lost my passport", "lang_pair": "ht-en", "context": "travel"},
    {"source": "I need a lawyer", "target": "Mwen bezwen yon avoka", "lang_pair": "en-ht", "context": "legal"},
    {"source": "Mwen bezwen yon avoka", "target": "I need a lawyer", "lang_pair": "ht-en", "context": "legal"},
    {"source": "It is an emergency", "target": "Se yon ijans", "lang_pair": "en-ht", "context": "emergency"},
    {"source": "Se yon ijans", "target": "It is an emergency", "lang_pair": "ht-en", "context": "emergency"},
    {"source": "I am lost", "target": "Mwen pèdi", "lang_pair": "en-ht", "context": "travel"},
    {"source": "Mwen pèdi", "target": "I am lost", "lang_pair": "ht-en", "context": "travel"},
    {"source": "Do you speak English", "target": "Eske ou pale angle", "lang_pair": "en-ht", "context": "general"},
    {"source": "Eske ou pale angle", "target": "Do you speak English", "lang_pair": "ht-en", "context": "general"},
    {"source": "Do you speak Haitian Creole", "target": "Eske ou pale kreyòl", "lang_pair": "en-ht", "context": "general"},
    {"source": "Eske ou pale kreyòl", "target": "Do you speak Haitian Creole", "lang_pair": "ht-en", "context": "general"},
    {"source": "I am diabetic", "target": "Mwen gen dyabèt", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen gen dyabèt", "target": "I am diabetic", "lang_pair": "ht-en", "context": "medical"},
    {"source": "I have a headache", "target": "Mwen gen maltèt", "lang_pair": "en-ht", "context": "medical"},
    {"source": "Mwen gen maltèt", "target": "I have a headache", "lang_pair": "ht-en", "context": "medical"},
    {"source": "Stop", "target": "Rete", "lang_pair": "en-ht", "context": "emergency"},
    {"source": "Rete", "target": "Stop", "lang_pair": "ht-en", "context": "emergency"},
    {"source": "Wait", "target": "Tann", "lang_pair": "en-ht", "context": "general"},
    {"source": "Tann", "target": "Wait", "lang_pair": "ht-en", "context": "general"},
]

# Short emergency phrases pre-warmed for TTS latency (EN + HT).
EMERGENCY_TTS_PREWARM: dict[str, list[str]] = {
    "en": [
        "I need a doctor.",
        "Call an ambulance.",
        "I need help.",
        "Please speak slowly.",
    ],
    "ht": [
        "Mwen bezwen yon doktè.",
        "Rele yon anbilans.",
        "Mwen bezwen èd.",
        "Tanpri pale dousman.",
    ],
}
