"""AILang transpiler — converts an AST to executable Python code."""
from typing import Any, List
from .ast_nodes import *


class TranspileError(Exception):
    pass


_INDENT = "    "


class Transpiler:
    def __init__(self):
        self._model_registry: dict = {}   # name -> ModelDecl
        self._agent_registry: dict = {}   # name -> AgentDecl
        self._indent_level = 0

    def indent(self) -> str:
        return _INDENT * self._indent_level

    def transpile(self, program: Program) -> str:
        lines = [
            "# Auto-generated by AILang transpiler",
            "import os as _os",
            "from ailang.stdlib import *",
            "from ailang.runtime_helpers import ask_model, make_agent_class, _add",
            "",
        ]

        for node in program.body:
            chunk = self.emit_top_level(node)
            if chunk:
                lines.append(chunk)

        return "\n".join(lines)

    def emit_top_level(self, node: Any) -> str:
        if isinstance(node, ModelDecl):
            self._model_registry[node.name] = node
            return (
                f"{node.name} = {{'provider': {node.provider!r}, "
                f"'name': {node.model_name!r}}}"
            )
        if isinstance(node, ConstDecl):
            return f"{node.name} = {self.emit_expr(node.value)}"
        if isinstance(node, FnDecl):
            return self.emit_fn(node)
        if isinstance(node, AgentDecl):
            self._agent_registry[node.name] = node
            return self.emit_agent(node)
        return ""

    # ------------------------------------------------------------------ #
    #  Functions                                                           #
    # ------------------------------------------------------------------ #

    def emit_fn(self, fn: FnDecl, indent_level: int = 0) -> str:
        self._indent_level = indent_level
        ind = self.indent()
        params = ", ".join(fn.params)
        lines = [f"{ind}def {fn.name}({params}):"]
        if not fn.body:
            lines.append(f"{ind}{_INDENT}pass")
        else:
            self._indent_level += 1
            for stmt in fn.body:
                lines.append(self.emit_stmt(stmt))
            self._indent_level -= 1
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    #  Agents                                                              #
    # ------------------------------------------------------------------ #

    def emit_agent(self, agent: AgentDecl) -> str:
        model = self._model_registry.get(agent.model_ref)
        model_dict = (
            f"{{'provider': {model.provider!r}, 'name': {model.model_name!r}}}"
            if model
            else f"{{'provider': 'anthropic', 'name': 'claude-haiku-4-5-20251001'}}"
        )
        instructions = agent.instructions or ""
        tools = agent.tools

        method_lines = []
        for method in agent.methods:
            method_lines.append(self.emit_fn(method, indent_level=1))

        methods_block = "\n\n".join(method_lines) if method_lines else f"{_INDENT}pass"

        return f"""{agent.name} = make_agent_class(
    name={agent.name!r},
    model={model_dict},
    instructions={instructions!r},
    tools={tools!r},
)

class _{agent.name}Methods:
{methods_block}

# Attach methods to agent instance
for _mname in dir(_{agent.name}Methods):
    if not _mname.startswith('_'):
        setattr({agent.name}, _mname, getattr(_{agent.name}Methods, _mname))
"""

    # ------------------------------------------------------------------ #
    #  Statements                                                          #
    # ------------------------------------------------------------------ #

    def emit_stmt(self, node: Any) -> str:
        ind = self.indent()
        if isinstance(node, ReturnStmt):
            return f"{ind}return {self.emit_expr(node.value)}"
        if isinstance(node, AssignStmt):
            return f"{ind}{node.name} = {self.emit_expr(node.value)}"
        if isinstance(node, ExprStmt):
            return f"{ind}{self.emit_expr(node.expr)}"
        if isinstance(node, IfStmt):
            return self.emit_if(node)
        if isinstance(node, ForStmt):
            return self.emit_for(node)
        if isinstance(node, BreakStmt):
            return f"{ind}break"
        return f"{ind}pass  # unknown stmt {type(node).__name__}"

    def emit_if(self, node: IfStmt) -> str:
        ind = self.indent()
        lines = [f"{ind}if {self.emit_expr(node.condition)}:"]
        self._indent_level += 1
        for s in node.then_body:
            lines.append(self.emit_stmt(s))
        if not node.then_body:
            lines.append(f"{self.indent()}pass")
        self._indent_level -= 1
        if node.else_body:
            lines.append(f"{ind}else:")
            self._indent_level += 1
            for s in node.else_body:
                lines.append(self.emit_stmt(s))
            if not node.else_body:
                lines.append(f"{self.indent()}pass")
            self._indent_level -= 1
        return "\n".join(lines)

    def emit_for(self, node: ForStmt) -> str:
        ind = self.indent()
        lines = [f"{ind}for {node.var} in ({self.emit_expr(node.iterable)} or []):"]
        self._indent_level += 1
        for s in node.body:
            lines.append(self.emit_stmt(s))
        if not node.body:
            lines.append(f"{self.indent()}pass")
        self._indent_level -= 1
        return "\n".join(lines)

    # ------------------------------------------------------------------ #
    #  Expressions                                                         #
    # ------------------------------------------------------------------ #

    def emit_expr(self, node: Any) -> str:
        if node is None:
            return "None"
        if isinstance(node, Literal):
            return repr(node.value)
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, BinOp):
            l = self.emit_expr(node.left)
            r = self.emit_expr(node.right)
            if node.op == "+":
                # runtime-safe addition — use helper
                return f"_add({l}, {r})"
            return f"({l} {node.op} {r})"
        if isinstance(node, UnaryOp):
            return f"({node.op} {self.emit_expr(node.operand)})"
        if isinstance(node, CallExpr):
            args = ", ".join(self.emit_expr(a) for a in node.args)
            # map AILang built-ins that clash with Python builtins
            name_map = {"print": "print_", "str": "str_", "int": "int_",
                        "float": "float_", "bool": "bool_", "format": "format_",
                        "slice": "slice"}
            fname = name_map.get(node.func, node.func)
            return f"{fname}({args})"
        if isinstance(node, MethodCallExpr):
            args = ", ".join(self.emit_expr(a) for a in node.args)
            return f"{node.obj}.{node.method}({args})"
        if isinstance(node, IndexExpr):
            obj = self.emit_expr(node.obj)
            idx = self.emit_expr(node.index)
            return f"({obj}[{idx}] if isinstance({obj}, (list, dict)) and {idx} in ({obj} if isinstance({obj}, dict) else range(len({obj}))) else None)"
        if isinstance(node, AskExpr):
            model_ref = node.model_ref
            prompt = self.emit_expr(node.prompt)
            return f"ask_model({model_ref}, {prompt})"
        if isinstance(node, FStringExpr):
            return self.emit_fstring(node)
        if isinstance(node, ListLiteral):
            elems = ", ".join(self.emit_expr(e) for e in node.elements)
            return f"[{elems}]"
        if isinstance(node, DictLiteral):
            pairs = ", ".join(
                f"{self.emit_expr(k)}: {self.emit_expr(v)}"
                for k, v in node.pairs
            )
            return "{" + pairs + "}"
        return repr(str(node))

    def emit_fstring(self, node: FStringExpr) -> str:
        parts = []
        for part in node.parts:
            if isinstance(part, Literal) and isinstance(part.value, str):
                parts.append(part.value.replace("{", "{{").replace("}", "}}"))
            else:
                parts.append("{" + self.emit_expr(part) + "}")
        raw = "".join(parts)
        return 'f"' + raw.replace('"', '\\"') + '"'
