import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050711",
  },
  page: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
  },
  pageCompact: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  interpreterPanel: {
    flex: 1,
    width: "100%",
    maxHeight: 780,
    alignSelf: "center",
    borderRadius: 28,
    padding: 16,
    backgroundColor: "#0a0f1d",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.22)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 10,
    gap: 12,
  },
  interpreterPanelCompact: {
    borderRadius: 22,
    padding: 12,
    gap: 8,
  },
  interpreterPanelTiny: {
    padding: 10,
    gap: 6,
  },
  topBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  topBarCompact: {
    minHeight: 42,
  },
  brand: {
    color: "#f8fafc",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
  },
  brandSubline: {
    color: "#9fb6d8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  connectionBadge: {
    minWidth: 104,
    maxWidth: 140,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
  },
  connectionDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  connectionText: {
    flexShrink: 1,
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
  },
  routeBand: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
  },
  routeBandCompact: {
    minHeight: 58,
    gap: 8,
  },
  routeSide: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: "#121a2d",
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.22)",
  },
  routeSideActive: {
    backgroundColor: "#0f2d2b",
    borderColor: "rgba(45, 212, 191, 0.58)",
  },
  routeSideCompact: {
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  routeCenter: {
    width: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: "#7dd3fc",
    alignSelf: "center",
    aspectRatio: 1,
  },
  routeCenterDisabled: {
    opacity: 0.42,
  },
  routeCenterPressed: {
    transform: [{ scale: 0.94 }],
  },
  routeCaption: {
    color: "#91a6c9",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  routeLanguage: {
    marginTop: 5,
    color: "#f8fafc",
    fontSize: 21,
    fontWeight: "900",
    letterSpacing: 0,
  },
  voiceButton: {
    width: 164,
    height: 164,
    borderRadius: 82,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#182033",
    borderWidth: 2,
    borderColor: "rgba(125, 211, 252, 0.42)",
    shadowColor: "#38bdf8",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 26,
    elevation: 12,
  },
  voiceButtonCompact: {
    width: 132,
    height: 132,
    borderRadius: 66,
  },
  voiceButtonTiny: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  voiceButtonListening: {
    backgroundColor: "#062e2a",
    borderColor: "rgba(52, 211, 153, 0.78)",
    shadowColor: "#34d399",
    shadowOpacity: 0.45,
  },
  voiceButtonArmed: {
    borderColor: "rgba(125, 211, 252, 0.72)",
    shadowOpacity: 0.38,
  },
  voiceButtonSpeaking: {
    backgroundColor: "#28163a",
    borderColor: "rgba(216, 180, 254, 0.7)",
    shadowColor: "#d8b4fe",
    shadowOpacity: 0.42,
  },
  voiceButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  voiceCore: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(5, 7, 17, 0.78)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    gap: 8,
  },
  voiceCoreCompact: {
    width: 98,
    height: 98,
    borderRadius: 49,
    gap: 6,
  },
  voiceCoreTiny: {
    width: 86,
    height: 86,
    borderRadius: 43,
    gap: 4,
  },
  voiceButtonText: {
    width: 92,
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 0,
  },
  flowRail: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  flowRailCompact: {
    minHeight: 31,
    gap: 6,
  },
  flowStep: {
    flex: 1,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
  },
  flowStepActive: {
    backgroundColor: "#bfdbfe",
    borderColor: "rgba(191, 219, 254, 0.78)",
  },
  flowStepText: {
    color: "#c7d2fe",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  flowStepTextActive: {
    color: "#07131f",
  },
  transcriptStack: {
    flex: 1,
    minHeight: 180,
    gap: 10,
  },
  transcriptStackCompact: {
    minHeight: 142,
    gap: 8,
  },
  transcriptStackTiny: {
    minHeight: 124,
    gap: 6,
  },
  transcriptLane: {
    flex: 1,
    minHeight: 82,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(129, 140, 248, 0.28)",
  },
  transcriptLaneCompact: {
    minHeight: 64,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 15,
  },
  translationLane: {
    flex: 1.12,
    minHeight: 98,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "#061f1c",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.34)",
  },
  translationLaneCompact: {
    minHeight: 74,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 15,
  },
  turnRail: {
    minHeight: 34,
    flexDirection: "row",
    gap: 6,
  },
  turnChip: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: 9,
    borderRadius: 12,
    backgroundColor: "#101827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
  },
  turnChipWarning: {
    backgroundColor: "#281d0b",
    borderColor: "rgba(245, 158, 11, 0.45)",
  },
  turnChipText: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  turnChipSpeaker: {
    color: "#67e8f9",
    fontWeight: "900",
  },
  laneLabel: {
    color: "#93a4bd",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  laneText: {
    marginTop: 7,
    color: "#f1f5f9",
    fontSize: 21,
    lineHeight: 26,
    fontWeight: "800",
  },
  translationText: {
    marginTop: 7,
    color: "#bbf7d0",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  lanePlaceholder: {
    color: "#6b7280",
  },
  statusStrip: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    borderRadius: 16,
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
  },
  statusStripCompact: {
    minHeight: 42,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  statusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  statusLine: {
    fontSize: 13,
    fontWeight: "900",
  },
  statusDetail: {
    marginTop: 2,
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
  },
  controlDock: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 7,
  },
  controlDockCompact: {
    minHeight: 56,
    gap: 5,
  },
  iconControl: {
    flex: 1,
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 6,
    borderRadius: 16,
    backgroundColor: "#121826",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
  },
  iconControlActive: {
    backgroundColor: "#a7f3d0",
    borderColor: "rgba(167, 243, 208, 0.78)",
  },
  iconControlDanger: {
    backgroundColor: "#24131b",
    borderColor: "rgba(251, 113, 133, 0.3)",
  },
  iconControlDisabled: {
    opacity: 0.42,
  },
  iconControlPressed: {
    transform: [{ scale: 0.97 }],
  },
  iconControlText: {
    color: "#dbeafe",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  iconControlTextActive: {
    color: "#07131f",
  },

  actionButton: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "transparent",
  },
  actionButton_primary: { backgroundColor: "#0891b2", borderColor: "rgba(103, 232, 249, 0.38)" },
  actionButton_success: { backgroundColor: "#059669", borderColor: "rgba(167, 243, 208, 0.38)" },
  actionButton_danger: { backgroundColor: "#dc2626", borderColor: "rgba(254, 202, 202, 0.28)" },
  actionButton_ghost: { backgroundColor: "rgba(15, 23, 42, 0.7)", borderColor: "rgba(148, 163, 184, 0.22)" },
  actionButtonDisabled: { opacity: 0.45 },
  actionButtonPressed: { transform: [{ scale: 0.98 }] },
  actionButtonText: { color: "#f8fafc", fontSize: 14, fontWeight: "900", textAlign: "center" },
  actionButtonTextGhost: { color: "#cbd5e1" },
  smallAction: { flex: 0, minHeight: 34, paddingHorizontal: 12 },

  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
  },
  topBarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  scrollPanel: {
    flex: 1,
    minHeight: 120,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 4,
  },
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
  },
  bannerError: {
    backgroundColor: "#1f1215",
    borderColor: "rgba(248, 113, 113, 0.45)",
  },
  bannerWarning: {
    backgroundColor: "#281d0b",
    borderColor: "rgba(245, 158, 11, 0.45)",
  },
  bannerText: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  bannerAction: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  bannerActionText: {
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: "900",
  },
  settingsOverlay: {
    flex: 1,
    backgroundColor: "#050711",
  },
  hintStrip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.9)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
  },
  hintStripText: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: "#050711",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  loadingScreenText: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "700",
  },
  offlineCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "#0c1a2e",
    borderWidth: 1,
    borderColor: "rgba(34, 211, 238, 0.35)",
  },
  offlineCtaText: {
    flex: 1,
    color: "#e0f2fe",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  offlineCtaBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#22d3ee",
  },
  offlineCtaBtnText: {
    color: "#07131f",
    fontSize: 12,
    fontWeight: "900",
  },
  routeFlag: {
    fontSize: 20,
    marginBottom: 2,
  },
  routeTapHint: {
    marginTop: 4,
    color: "#64748b",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  voiceButtonBusy: {
    opacity: 0.85,
  },
  toast: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 18,
    zIndex: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "rgba(15, 23, 42, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.28)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  toastText: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
  },
  laneHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  laneActionBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
  },
  contextChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(34, 211, 238, 0.28)",
  },
  contextChipText: {
    color: "#a5f3fc",
    fontSize: 11,
    fontWeight: "800",
  },
});
