import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#03050a",
  },
  pageGradient: {
    flex: 1,
    position: "relative",
  },
  cosmicGlow: {
    position: "absolute",
    top: "8%",
    left: "-20%",
    right: "-20%",
    height: "42%",
    borderRadius: 999,
    backgroundColor: "rgba(20, 184, 166, 0.07)",
    opacity: 0.85,
  },
  cosmicGlowBlue: {
    position: "absolute",
    bottom: "12%",
    left: "-10%",
    right: "-10%",
    height: "28%",
    borderRadius: 999,
    backgroundColor: "rgba(56, 189, 248, 0.05)",
    opacity: 0.7,
  },
  cosmicGridDriftWrap: {
    ...StyleSheet.absoluteFillObject,
  },
  cosmicGridOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.35,
  },
  cosmicGridLineH: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(103, 232, 249, 0.06)",
  },
  cosmicGridLineV: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: "rgba(125, 211, 252, 0.04)",
  },
  page: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: "center",
    backgroundColor: "#03050a",
  },
  pageCompact: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  interpreterPanel: {
    flex: 1,
    width: "100%",
    maxHeight: 820,
    alignSelf: "center",
    borderRadius: 36,
    padding: 16,
    backgroundColor: "rgba(8, 14, 30, 0.94)",
    borderWidth: 1,
    borderColor: "rgba(125, 211, 252, 0.18)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 32 },
    shadowOpacity: 0.55,
    shadowRadius: 48,
    elevation: 18,
    gap: 10,
    overflow: "hidden",
  },
  interpreterPanelCompact: {
    borderRadius: 22,
    padding: 12,
    gap: 8,
  },
  interpreterPanelTiny: {
    padding: 10,
    gap: 6,
  },
  interpreterPanelOnline: {
    borderColor: "rgba(52, 211, 153, 0.38)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.28,
    shadowRadius: 40,
  },
  interpreterPanelListening: {
    borderColor: "rgba(45, 212, 191, 0.45)",
    shadowColor: "#34d399",
    shadowOpacity: 0.32,
    shadowRadius: 44,
  },
  panelTopShine: {
    position: "absolute",
    top: 0,
    left: 24,
    right: 24,
    height: 1,
    zIndex: 2,
  },
  panelBottomShine: {
    position: "absolute",
    bottom: 0,
    left: 32,
    right: 32,
    height: 1,
    zIndex: 2,
  },
  panelListeningPulse: {
    position: "absolute",
    top: 2,
    left: 2,
    right: 2,
    bottom: 2,
    borderRadius: 34,
    borderWidth: 1.5,
    borderColor: "rgba(45, 212, 191, 0.55)",
    zIndex: 1,
  },
  panelAura: {
    position: "absolute",
    top: -40,
    left: "12%",
    right: "12%",
    height: 120,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.06)",
    opacity: 0.9,
  },
  panelAuraOnline: {
    backgroundColor: "rgba(52, 211, 153, 0.08)",
  },
  topBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  topBarCompact: {
    minHeight: 42,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  brand: {
    color: "#f8fafc",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
  },
  brandAccent: {
    color: "#67e8f9",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
    textShadowColor: "rgba(34, 211, 238, 0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  brandSubline: {
    color: "#9fb6d8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  connectionBadge: {
    minWidth: 108,
    maxWidth: 168,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
  },
  connectionBadgePulsing: {
    shadowColor: "#34d399",
    shadowOpacity: 0.2,
  },
  connectionBadgeOnline: {
    borderColor: "rgba(52, 211, 153, 0.42)",
    backgroundColor: "rgba(6, 44, 38, 0.92)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  connectionBadgeOffline: {
    borderColor: "rgba(248, 113, 113, 0.32)",
    backgroundColor: "rgba(31, 18, 21, 0.92)",
    shadowColor: "#f87171",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  connectionBadgeWarning: {
    borderColor: "rgba(245, 158, 11, 0.45)",
    backgroundColor: "rgba(42, 28, 8, 0.94)",
    shadowColor: "#f59e0b",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
  },
  connectionBadgePressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  connectionDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  connectionText: {
    flexShrink: 1,
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
  },
  routeBand: {
    minHeight: 52,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 4,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.42)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.1)",
    overflow: "hidden",
    position: "relative",
  },
  routeBandShine: {
    position: "absolute",
    top: 0,
    left: 12,
    right: 12,
    height: 1,
    zIndex: 1,
  },
  routeSideContent: {
    alignItems: "center",
    gap: 2,
    flex: 1,
    minWidth: 0,
  },
  routeSideRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minWidth: 0,
    width: "100%",
  },
  routeBandCompact: {
    minHeight: 58,
    gap: 8,
  },
  routeSide: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(12, 18, 38, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  routeSideActive: {
    backgroundColor: "rgba(15, 45, 43, 0.95)",
    borderColor: "rgba(45, 212, 191, 0.62)",
    shadowColor: "#2dd4bf",
    shadowOpacity: 0.22,
  },
  routeSideSource: {
    backgroundColor: "rgba(15, 23, 42, 0.4)",
    borderColor: "rgba(148, 163, 184, 0.12)",
  },
  routeSideTarget: {
    backgroundColor: "rgba(20, 184, 166, 0.18)",
    borderColor: "rgba(153, 246, 228, 0.22)",
  },
  routeSideCompact: {
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  routeSidePressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.94,
  },
  routeCenter: {
    width: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: "#67e8f9",
    alignSelf: "center",
    aspectRatio: 1,
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  routeCenterDisabled: {
    opacity: 0.42,
  },
  routeCenterPressed: {
    transform: [{ scale: 0.94 }],
  },
  routeCenterBridging: {
    backgroundColor: "#5eead4",
    shadowColor: "#2dd4bf",
  },
  routeCaption: {
    color: "#91a6c9",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  routeCaptionTarget: {
    color: "#5eead4",
  },
  routeLanguage: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0,
  },
  routeLanguageActive: {
    color: "#a5f3fc",
    textShadowColor: "rgba(34, 211, 238, 0.35)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  voiceButton: {
    width: 164,
    height: 164,
    borderRadius: 82,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#182033",
    borderWidth: 2,
    borderColor: "rgba(125, 211, 252, 0.42)",
    shadowColor: "#38bdf8",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 26,
    elevation: 12,
  },
  voiceButtonCompact: {
    width: 132,
    height: 132,
    borderRadius: 66,
  },
  voiceButtonTiny: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  voiceButtonListening: {
    backgroundColor: "#062e2a",
    borderColor: "rgba(52, 211, 153, 0.78)",
    shadowColor: "#34d399",
    shadowOpacity: 0.45,
  },
  voiceButtonArmed: {
    borderColor: "rgba(125, 211, 252, 0.72)",
    shadowOpacity: 0.38,
  },
  voiceButtonOffline: {
    backgroundColor: "#2a1d08",
    borderColor: "rgba(251, 191, 36, 0.72)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.35,
  },
  voiceButtonSpeaking: {
    backgroundColor: "#28163a",
    borderColor: "rgba(216, 180, 254, 0.7)",
    shadowColor: "#d8b4fe",
    shadowOpacity: 0.42,
  },
  voiceButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  voiceButtonDisabled: {
    opacity: 0.52,
    borderColor: "rgba(148, 163, 184, 0.28)",
    shadowOpacity: 0.08,
  },
  voiceCore: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(5, 7, 17, 0.78)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.32,
    shadowRadius: 10,
    elevation: 4,
  },
  voiceCoreCompact: {
    width: 98,
    height: 98,
    borderRadius: 49,
    gap: 6,
  },
  voiceCoreTiny: {
    width: 86,
    height: 86,
    borderRadius: 43,
    gap: 4,
  },
  voiceButtonText: {
    width: 92,
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 0,
  },
  flowRailWrap: {
    padding: 3,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.28)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.08)",
  },
  flowRailWrapCompact: {
    padding: 2,
  },
  flowRail: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  flowRailItem: {
    flex: 1,
    minWidth: 0,
  },
  flowConnectorWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minWidth: 28,
  },
  flowConnectorLine: {
    flex: 1,
    height: 1,
    borderRadius: 1,
    backgroundColor: "rgba(45, 212, 191, 0.45)",
    opacity: 0.25,
  },
  flowConnector: {
    width: 14,
    height: 2,
    borderRadius: 1,
    backgroundColor: "rgba(148, 163, 184, 0.22)",
  },
  flowConnectorActive: {
    backgroundColor: "rgba(45, 212, 191, 0.55)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 2,
  },
  flowConnectorHubWrap: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 16,
  },
  flowConnectorHub: {
    position: "absolute",
    fontSize: 9,
    lineHeight: 10,
    color: "rgba(148, 163, 184, 0.55)",
    fontWeight: "700",
  },
  flowConnectorHubActive: {
    color: "rgba(103, 232, 249, 0.92)",
    textShadowColor: "rgba(45, 212, 191, 0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  flowRailCompact: {
    minHeight: 31,
    gap: 6,
  },
  flowRailMuted: {
    opacity: 0.45,
  },
  flowStep: {
    flex: 1,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: "rgba(17, 24, 39, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    opacity: 0.82,
    overflow: "hidden",
    position: "relative",
  },
  flowStepGlow: {
    position: "absolute",
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: 999,
    backgroundColor: "#2dd4bf",
  },
  flowStepActive: {
    backgroundColor: "rgba(20, 184, 166, 0.32)",
    borderColor: "rgba(45, 212, 191, 0.62)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 5,
    transform: [{ scale: 1.02 }],
    opacity: 1,
  },
  flowStepText: {
    color: "#c7d2fe",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  flowStepTextActive: {
    color: "#ecfdf5",
  },
  transcriptStack: {
    flex: 1,
    minHeight: 180,
    gap: 10,
  },
  transcriptStackCompact: {
    minHeight: 142,
    gap: 8,
  },
  transcriptStackTiny: {
    minHeight: 124,
    gap: 6,
  },
  transcriptLane: {
    flex: 1,
    minHeight: 88,
    flexDirection: "row",
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: "rgba(12, 18, 38, 0.56)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.1)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 4,
  },
  transcriptLaneCompact: {
    minHeight: 64,
    borderRadius: 15,
  },
  transcriptLaneLive: {
    borderColor: "rgba(96, 165, 250, 0.32)",
    backgroundColor: "rgba(15, 23, 42, 0.72)",
    shadowColor: "#3b82f6",
    shadowOpacity: 0.22,
    shadowRadius: 18,
  },
  laneBridgeSpan: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    height: 22,
    marginVertical: -2,
  },
  laneBridgeLine: {
    flex: 1,
    height: 2,
    borderRadius: 999,
    backgroundColor: "rgba(45, 212, 191, 0.22)",
    opacity: 0.35,
  },
  laneBridgeHub: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(103, 232, 249, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.18)",
  },
  laneBridgeHubActive: {
    borderColor: "rgba(45, 212, 191, 0.45)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 2,
  },
  translationLane: {
    flex: 1.12,
    minHeight: 96,
    flexDirection: "row",
    overflow: "hidden",
    borderRadius: 20,
    backgroundColor: "rgba(12, 18, 38, 0.56)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 4,
  },
  translationLaneCompact: {
    minHeight: 74,
    borderRadius: 15,
  },
  translationLaneLive: {
    borderColor: "rgba(45, 212, 191, 0.36)",
    backgroundColor: "rgba(6, 78, 59, 0.22)",
    shadowColor: "#14b8a6",
    shadowOpacity: 0.28,
    shadowRadius: 20,
  },
  translationLaneSpeaking: {
    borderColor: "rgba(251, 191, 36, 0.36)",
    backgroundColor: "rgba(120, 53, 15, 0.18)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  translationLaneBusy: {
    borderColor: "rgba(251, 191, 36, 0.45)",
    backgroundColor: "rgba(40, 28, 8, 0.92)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.22,
    shadowRadius: 14,
  },
  translationLaneCertAdvisory: {
    borderColor: "rgba(251, 191, 36, 0.48)",
    backgroundColor: "rgba(42, 28, 8, 0.42)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.18,
    shadowRadius: 14,
  },
  translationLaneCertRequired: {
    borderColor: "rgba(251, 146, 60, 0.55)",
    backgroundColor: "rgba(42, 16, 8, 0.52)",
    shadowColor: "#fb923c",
    shadowOpacity: 0.22,
    shadowRadius: 16,
  },
  turnRailWrap: {
    gap: 6,
    marginTop: 2,
  },
  turnRailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 2,
  },
  turnRailHeaderText: {
    color: "rgba(148, 163, 184, 0.72)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  turnRail: {
    minHeight: 34,
    flexDirection: "row",
    gap: 8,
  },
  turnChip: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: 9,
    paddingVertical: 8,
    paddingLeft: 12,
    borderRadius: 14,
    backgroundColor: "rgba(16, 24, 39, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
    overflow: "hidden",
    position: "relative",
  },
  turnChipAccent: {
    position: "absolute",
    left: 0,
    top: 8,
    bottom: 8,
    width: 3,
    borderRadius: 2,
    backgroundColor: "rgba(148, 163, 184, 0.35)",
  },
  turnChipAccentActive: {
    backgroundColor: "#22d3ee",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  turnChipAccentWarning: {
    backgroundColor: "#fbbf24",
  },
  turnChipLiveDot: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#34d399",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 2,
  },
  turnChipActive: {
    borderColor: "rgba(103, 232, 249, 0.42)",
    backgroundColor: "rgba(8, 47, 73, 0.72)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.16,
    shadowRadius: 8,
  },
  turnChipWarning: {
    backgroundColor: "#281d0b",
    borderColor: "rgba(245, 158, 11, 0.45)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.12,
  },
  turnChipCertRequired: {
    backgroundColor: "#2a1810",
    borderColor: "rgba(251, 146, 60, 0.5)",
    shadowColor: "#fb923c",
    shadowOpacity: 0.14,
  },
  turnChipCertBadge: {
    position: "absolute",
    top: 6,
    right: 8,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251, 191, 36, 0.18)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.35)",
  },
  turnChipText: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  turnChipSpeaker: {
    color: "#67e8f9",
    fontWeight: "900",
  },
  turnChipSource: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
    marginTop: 2,
  },
  turnChipBridgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
    marginBottom: 1,
  },
  turnChipBridgeLine: {
    flex: 1,
    height: 1,
    borderRadius: 999,
    backgroundColor: "rgba(45, 212, 191, 0.35)",
  },
  turnChipBridged: {
    color: "#a7f3d0",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 15,
    fontStyle: "italic",
  },
  laneLabel: {
    color: "#93a4bd",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  laneLabelFlex: {
    flex: 1,
    minWidth: 0,
  },
  topBarBrand: {
    flex: 1,
    minWidth: 0,
  },
  laneLabelLive: {
    color: "#67e8f9",
    textShadowColor: "rgba(34, 211, 238, 0.35)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  laneAttentionBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  laneAttentionBadgeAdvisory: {
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    borderColor: "rgba(251, 191, 36, 0.35)",
  },
  laneAttentionBadgeRequired: {
    backgroundColor: "rgba(251, 146, 60, 0.14)",
    borderColor: "rgba(251, 146, 60, 0.42)",
  },
  laneAttentionBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.4,
    color: "#fde68a",
  },
  laneText: {
    marginTop: 7,
    color: "#f1f5f9",
    fontSize: 21,
    lineHeight: 26,
    fontWeight: "800",
  },
  translationText: {
    marginTop: 7,
    color: "#a7f3d0",
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
  },
  lanePlaceholder: {
    color: "#64748b",
    fontStyle: "italic",
    fontWeight: "600",
  },
  statusStrip: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.16)",
    overflow: "hidden",
    position: "relative",
  },
  statusStripGlow: {
    position: "absolute",
    top: -8,
    left: -8,
    right: -8,
    bottom: -8,
    borderRadius: 20,
  },
  statusStripShine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    zIndex: 1,
  },
  statusStripAccent: {
    position: "absolute",
    left: 0,
    top: 10,
    bottom: 10,
    width: 3,
    borderRadius: 2,
    opacity: 0.9,
  },
  statusStripCompact: {
    minHeight: 42,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  statusStripPressed: {
    backgroundColor: "rgba(30, 41, 59, 0.95)",
    borderColor: "rgba(103, 232, 249, 0.32)",
  },
  statusStripOnline: {
    backgroundColor: "rgba(6, 31, 28, 0.88)",
    borderColor: "rgba(52, 211, 153, 0.28)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  statusStripOffline: {
    backgroundColor: "rgba(31, 18, 21, 0.92)",
    borderColor: "rgba(248, 113, 113, 0.35)",
  },
  statusStripWarning: {
    backgroundColor: "rgba(42, 28, 8, 0.94)",
    borderColor: "rgba(245, 158, 11, 0.42)",
  },
  statusStripListening: {
    backgroundColor: "rgba(6, 44, 38, 0.92)",
    borderColor: "rgba(52, 211, 153, 0.42)",
    shadowColor: "#34d399",
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  statusStripTranslating: {
    backgroundColor: "rgba(42, 28, 8, 0.9)",
    borderColor: "rgba(251, 191, 36, 0.38)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  statusStripSpeaking: {
    backgroundColor: "rgba(40, 22, 58, 0.88)",
    borderColor: "rgba(216, 180, 254, 0.35)",
    shadowColor: "#d8b4fe",
    shadowOpacity: 0.16,
    shadowRadius: 12,
  },
  statusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  statusLine: {
    fontSize: 13,
    fontWeight: "900",
  },
  statusDetail: {
    marginTop: 2,
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
  },
  statusDetailOffline: {
    color: "#cbd5e1",
    fontSize: 12,
  },
  statusDetailMuted: {
    marginTop: 2,
    color: "#64748b",
    fontSize: 10,
    fontWeight: "600",
  },
  statusStripDebugChip: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: "rgba(103, 232, 249, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  statusStripDebugChipText: {
    color: "#67e8f9",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.08,
  },
  controlDock: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 0,
    padding: 4,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.42)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.1)",
  },
  controlDockCompact: {
    minHeight: 56,
  },
  controlDockItemWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "stretch",
    minWidth: 0,
  },
  controlDockDivider: {
    width: 1,
    alignSelf: "stretch",
    marginVertical: 10,
    backgroundColor: "rgba(148, 163, 184, 0.14)",
  },
  iconControlInDock: {
    flex: 1,
    minWidth: 0,
  },
  iconControl: {
    flex: 1,
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: "rgba(12, 18, 38, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  iconControlActive: {
    backgroundColor: "rgba(20, 184, 166, 0.32)",
    borderColor: "rgba(45, 212, 191, 0.55)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
    overflow: "hidden",
    position: "relative",
  },
  iconControlBridgeLinked: {
    backgroundColor: "rgba(56, 189, 248, 0.28)",
    borderColor: "rgba(125, 211, 252, 0.62)",
    shadowColor: "#38bdf8",
  },
  iconControlGlow: {
    position: "absolute",
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 999,
    backgroundColor: "rgba(45, 212, 191, 0.18)",
  },
  iconControlBridgeGlow: {
    backgroundColor: "rgba(56, 189, 248, 0.22)",
  },
  iconControlUrgent: {
    backgroundColor: "rgba(69, 45, 8, 0.95)",
    borderColor: "rgba(251, 191, 36, 0.55)",
    shadowColor: "#fbbf24",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 4,
  },
  iconControlTextUrgent: {
    color: "#fde68a",
  },
  iconControlDanger: {
    backgroundColor: "#24131b",
    borderColor: "rgba(251, 113, 133, 0.38)",
    shadowColor: "#fb7185",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  iconControlDisabled: {
    opacity: 0.42,
  },
  iconControlPressed: {
    transform: [{ scale: 0.97 }],
    borderColor: "rgba(103, 232, 249, 0.35)",
    backgroundColor: "rgba(30, 41, 59, 0.95)",
  },
  iconControlText: {
    color: "#dbeafe",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  iconControlTextActive: {
    color: "#07131f",
  },

  actionButton: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "transparent",
  },
  actionButton_primary: {
    backgroundColor: "#0891b2",
    borderColor: "rgba(103, 232, 249, 0.38)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButton_success: {
    backgroundColor: "#059669",
    borderColor: "rgba(167, 243, 208, 0.38)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButton_danger: {
    backgroundColor: "#dc2626",
    borderColor: "rgba(254, 202, 202, 0.28)",
    shadowColor: "#f87171",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButton_ghost: { backgroundColor: "rgba(15, 23, 42, 0.7)", borderColor: "rgba(148, 163, 184, 0.22)" },
  actionButtonDisabled: { opacity: 0.45 },
  actionButtonPressed: { transform: [{ scale: 0.98 }] },
  actionButtonText: { color: "#f8fafc", fontSize: 14, fontWeight: "900", textAlign: "center" },
  actionButtonTextGhost: { color: "#cbd5e1" },
  smallAction: { flex: 0, minHeight: 34, paddingHorizontal: 12 },

  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(17, 24, 39, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  settingsBtnPressed: {
    backgroundColor: "rgba(30, 41, 59, 0.95)",
    borderColor: "rgba(103, 232, 249, 0.32)",
    transform: [{ scale: 0.96 }],
  },
  topBarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  scrollPanel: {
    flex: 1,
    minHeight: 120,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.12)",
    backgroundColor: "rgba(2, 6, 23, 0.42)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
    overflow: "hidden",
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 12,
  },
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
  },
  bannerAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    opacity: 0.9,
  },
  bannerIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  bannerIconError: {
    backgroundColor: "rgba(248, 113, 113, 0.1)",
    borderColor: "rgba(248, 113, 113, 0.28)",
  },
  bannerIconWarning: {
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderColor: "rgba(251, 191, 36, 0.28)",
  },
  bannerError: {
    backgroundColor: "rgba(31, 18, 21, 0.96)",
    borderColor: "rgba(248, 113, 113, 0.45)",
    shadowColor: "#f87171",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  bannerWarning: {
    backgroundColor: "rgba(40, 29, 11, 0.96)",
    borderColor: "rgba(245, 158, 11, 0.45)",
    shadowColor: "#fbbf24",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  certBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginHorizontal: 0,
    marginBottom: 0,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
  },
  certBannerAdvisory: {
    backgroundColor: "rgba(40, 29, 11, 0.96)",
    borderColor: "rgba(245, 158, 11, 0.45)",
  },
  certBannerRequired: {
    backgroundColor: "rgba(42, 24, 16, 0.97)",
    borderColor: "rgba(251, 146, 60, 0.5)",
  },
  certBannerAccent: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
  },
  certBannerIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  certBannerIconAdvisory: {
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderColor: "rgba(251, 191, 36, 0.28)",
  },
  certBannerIconRequired: {
    backgroundColor: "rgba(251, 146, 60, 0.12)",
    borderColor: "rgba(251, 146, 60, 0.32)",
  },
  certBannerCopy: {
    flex: 1,
    gap: 2,
  },
  certBannerTitle: {
    color: "#f8fafc",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
    textTransform: "uppercase",
  },
  certBannerText: {
    color: "rgba(248, 250, 252, 0.92)",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  certBannerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  certBannerAction: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.35)",
  },
  certBannerActionPressed: {
    opacity: 0.82,
  },
  certBannerActionText: {
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: "700",
  },
  certBannerDismiss: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(148, 163, 184, 0.12)",
  },
  bannerText: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  bannerAction: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.35)",
  },
  bannerActionText: {
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: "900",
  },
  bannerActionPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.97 }],
  },
  bannerDismissPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.92 }],
  },
  settingsOverlay: {
    flex: 1,
    backgroundColor: "#03050a",
  },
  settingsScroll: {
    flex: 1,
    backgroundColor: "#050711",
  },
  hintStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(12, 20, 38, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.2)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  hintStripIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.12)",
  },
  hintStripText: {
    flex: 1,
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: "#03050a",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    paddingHorizontal: 24,
    position: "relative",
    overflow: "hidden",
  },
  loadingCosmicGlow: {
    position: "absolute",
    top: "18%",
    left: "-15%",
    right: "-15%",
    height: "38%",
    borderRadius: 999,
    backgroundColor: "rgba(20, 184, 166, 0.08)",
  },
  loadingCosmicGlowBlue: {
    position: "absolute",
    bottom: "16%",
    left: "-10%",
    right: "-10%",
    height: "24%",
    borderRadius: 999,
    backgroundColor: "rgba(56, 189, 248, 0.06)",
  },
  loadingBrandWrap: {
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  loadingOrbRing: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.35)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 18,
    elevation: 6,
  },
  loadingOrbCore: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(31, 41, 55, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  loadingOrbMic: {
    fontSize: 28,
  },
  loadingScreenText: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 280,
    letterSpacing: 0.2,
  },
  voiceButtonWrap: {
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  stopListeningBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.4)",
    backgroundColor: "rgba(127, 29, 29, 0.28)",
    shadowColor: "#f87171",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
    overflow: "hidden",
    position: "relative",
  },
  stopListeningGlow: {
    position: "absolute",
    top: -4,
    left: -4,
    right: -4,
    bottom: -4,
    borderRadius: 999,
    backgroundColor: "#f87171",
  },
  stopListeningIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(248, 113, 113, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.22)",
  },
  stopListeningBtnPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  stopListeningText: {
    color: "#fecaca",
    fontSize: 13,
    fontWeight: "800",
  },
  voicePulseRing: {
    position: "absolute",
    width: 196,
    height: 196,
    borderRadius: 98,
    borderWidth: 2,
    borderColor: "rgba(52, 211, 153, 0.45)",
    backgroundColor: "rgba(52, 211, 153, 0.06)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 6,
  },
  voicePulseRingCompact: {
    width: 160,
    height: 160,
    borderRadius: 80,
  },
  voicePulseRingTiny: {
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  offlineCta: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 18,
    backgroundColor: "rgba(18, 12, 28, 0.98)",
    borderWidth: 1.5,
    borderColor: "rgba(248, 113, 113, 0.42)",
    shadowColor: "#f87171",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 5,
    overflow: "hidden",
    position: "relative",
  },
  offlineCtaShine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    zIndex: 1,
  },
  offlineCtaAccent: {
    position: "absolute",
    left: 0,
    top: 14,
    bottom: 14,
    width: 3,
    borderRadius: 2,
    backgroundColor: "#f87171",
    opacity: 0.9,
  },
  offlineCtaBtnSecondaryBlock: {
    marginTop: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
  },
  offlineCtaTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  offlineCtaTitleText: {
    flex: 1,
    gap: 2,
  },
  offlineCtaTitle: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "900",
  },
  offlineCtaMeta: {
    color: "#67e8f9",
    fontSize: 11,
    fontWeight: "800",
  },
  offlineCtaActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  offlineCtaBtnPrimary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "#22d3ee",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.55)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 5,
  },
  offlineCtaBtnPrimaryText: {
    color: "#07131f",
    fontSize: 15,
    fontWeight: "900",
  },
  offlineCtaIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  offlineCtaText: {
    flex: 1,
    color: "#e0f2fe",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  offlineCtaBtnSecondary: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(15, 23, 42, 0.9)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.35)",
  },
  offlineCtaBtnSecondaryText: {
    color: "#e2e8f0",
    fontSize: 12,
    fontWeight: "800",
  },
  offlineCtaBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#22d3ee",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.45)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  offlineCtaBtnPressed: {
    transform: [{ scale: 0.97 }],
    opacity: 0.92,
  },
  offlineCtaBtnText: {
    color: "#07131f",
    fontSize: 12,
    fontWeight: "900",
  },
  routeFlag: {
    fontSize: 18,
  },
  routeTapHint: {
    marginTop: 4,
    color: "#64748b",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  voiceButtonBusy: {
    opacity: 0.85,
  },
  toast: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 28,
    zIndex: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.28)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
    overflow: "hidden",
  },
  toastGlow: {
    position: "absolute",
    top: -8,
    left: -8,
    right: -8,
    bottom: -8,
    borderRadius: 20,
    opacity: 0,
  },
  toastAccent: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    height: 2,
    opacity: 0.85,
  },
  debugDetailChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    paddingHorizontal: 2,
    marginTop: -2,
    marginBottom: 2,
  },
  debugDetailChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(103, 232, 249, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.22)",
  },
  debugDetailChipText: {
    color: "#7dd3fc",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.04,
  },
  debugInsightsPanel: {
    marginTop: 4,
    marginBottom: 6,
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.55)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.18)",
    gap: 8,
  },
  sessionInsightsPanel: {
    backgroundColor: "rgba(7, 17, 31, 0.72)",
    borderColor: "rgba(45, 212, 191, 0.22)",
  },
  debugInsightsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  debugInsightsTitle: {
    color: "#94a3b8",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.12,
    textTransform: "uppercase",
  },
  debugInsightsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  debugInsightChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(103, 232, 249, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.2)",
    maxWidth: "100%",
  },
  debugInsightChipLive: {
    backgroundColor: "rgba(45, 212, 191, 0.12)",
    borderColor: "rgba(45, 212, 191, 0.35)",
  },
  debugInsightChipWarn: {
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderColor: "rgba(251, 191, 36, 0.3)",
  },
  debugInsightChipText: {
    color: "#bae6fd",
    fontSize: 10,
    fontWeight: "700",
    flexShrink: 1,
  },
  toastIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.9)",
    borderWidth: 1,
  },
  toastText: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  toastSuccess: {
    borderColor: "rgba(52, 211, 153, 0.45)",
    shadowColor: "#34d399",
    shadowOpacity: 0.22,
  },
  toastError: {
    borderColor: "rgba(248, 113, 113, 0.45)",
    shadowColor: "#f87171",
    shadowOpacity: 0.22,
  },
  toastInfo: {
    borderColor: "rgba(103, 232, 249, 0.35)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.15,
  },
  laneHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  laneActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  laneActionBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
    overflow: "hidden",
  },
  laneActionBtnInner: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  laneActionBtnPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.94 }],
  },
  laneStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
  },
  laneStatusBadgeSource: {
    backgroundColor: "rgba(103, 232, 249, 0.1)",
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  laneStatusBadgeTarget: {
    backgroundColor: "rgba(52, 211, 153, 0.1)",
    borderColor: "rgba(52, 211, 153, 0.28)",
  },
  laneStatusBadgeBusy: {
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderColor: "rgba(251, 191, 36, 0.32)",
  },
  laneStatusBadgeDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#34d399",
  },
  laneStatusBadgeText: {
    color: "#a5f3fc",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.1,
  },
  laneStatusBadgeTextBusy: {
    color: "#fde68a",
  },
  contextChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(34, 211, 238, 0.28)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
    position: "relative",
    overflow: "hidden",
  },
  contextChipDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#67e8f9",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.7,
    shadowRadius: 4,
    elevation: 2,
  },
  contextChipText: {
    color: "#a5f3fc",
    fontSize: 11,
    fontWeight: "800",
  },

  connectionStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.32)",
    backgroundColor: "rgba(6, 44, 38, 0.55)",
    overflow: "hidden",
    position: "relative",
  },
  connectionStripGlow: {
    position: "absolute",
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 999,
    backgroundColor: "#34d399",
  },
  connectionStripListening: {
    borderColor: "rgba(52, 211, 153, 0.48)",
    backgroundColor: "rgba(6, 52, 44, 0.72)",
  },
  connectionStripSpeaking: {
    borderColor: "rgba(251, 191, 36, 0.38)",
    backgroundColor: "rgba(42, 28, 8, 0.62)",
  },
  connectionStripOffline: {
    borderColor: "rgba(248, 113, 113, 0.32)",
    backgroundColor: "rgba(31, 18, 21, 0.72)",
  },
  connectionStripText: {
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  connectionStripTextOffline: {
    color: "#fca5a5",
  },
  connectionStripReconnecting: {
    borderColor: "rgba(251, 191, 36, 0.42)",
    backgroundColor: "rgba(42, 28, 8, 0.72)",
  },

  qualityAlertStack: {
    marginHorizontal: 14,
    marginBottom: 6,
    gap: 6,
  },
  brainRepairPanelInline: {
    marginHorizontal: 0,
    marginBottom: 8,
  },

  clarifyPill: {
    marginHorizontal: 0,
    marginBottom: 0,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.42)",
    backgroundColor: "rgba(40, 29, 11, 0.96)",
    gap: 8,
  },
  clarifyPillRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  clarifyPillIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    marginTop: 1,
  },
  clarifyPillBody: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  clarifyPillText: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  clarifyPillActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  clarifyPillPrimary: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(52, 211, 153, 0.18)",
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.38)",
  },
  clarifyPillSecondary: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(148, 163, 184, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
  },
  clarifyPillPressed: {
    opacity: 0.82,
  },
  clarifyPillPrimaryText: {
    color: "#6ee7b7",
    fontSize: 12,
    fontWeight: "800",
  },
  clarifyPillSecondaryText: {
    color: "rgba(226, 232, 240, 0.88)",
    fontSize: 12,
    fontWeight: "700",
  },

  brainRepairPanel: {
    marginHorizontal: 0,
    marginBottom: 0,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
    backgroundColor: "rgba(8, 28, 36, 0.82)",
    gap: 8,
  },
  brainRepairHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  brainRepairTitle: {
    flex: 1,
    color: "#67e8f9",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  brainRepairRisk: {
    color: "#fbbf24",
    fontSize: 11,
    fontWeight: "800",
  },
  brainRepairMessage: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  brainRepairChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  brainRepairChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.28)",
  },
  brainRepairChipText: {
    color: "#fde68a",
    fontSize: 11,
    fontWeight: "700",
  },
  brainRepairActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  brainRepairAction: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.32)",
  },
  brainRepairActionPressed: {
    opacity: 0.82,
  },
  brainRepairActionText: {
    color: "#67e8f9",
    fontSize: 11,
    fontWeight: "700",
  },

  neoHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 56,
    paddingHorizontal: 2,
  },
  neoHeaderSide: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  neoHeaderSideRight: {
    justifyContent: "flex-end",
  },
  neoHeaderSpacer: {
    width: 1,
  },
  neoBrand: {
    alignItems: "center",
    gap: 3,
    position: "relative",
    overflow: "visible",
  },
  neoBrandGlow: {
    position: "absolute",
    top: -8,
    left: -16,
    right: -16,
    bottom: -6,
    borderRadius: 999,
    backgroundColor: "#2dd4bf",
  },
  neoBrandCompact: {
    gap: 2,
  },
  neoBrandLive: {
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
  },
  neoMarkWord: {
    color: "#67e8f9",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 1.5,
    textShadowColor: "rgba(34, 211, 238, 0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  neoMarkWordCompact: {
    fontSize: 22,
    letterSpacing: 1.2,
  },
  neoTitleRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 1,
  },
  neoMarkA: {
    color: "#67e8f9",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 4,
    textShadowColor: "rgba(34, 211, 238, 0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  neoMarkN: {
    color: "#f8fafc",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 4,
  },
  neoMarkI: {
    color: "#f0abfc",
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 4,
    textShadowColor: "rgba(244, 114, 182, 0.35)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  neoMarkCompact: {
    fontSize: 22,
    letterSpacing: 3,
  },
  neoSub: {
    color: "rgba(148, 163, 184, 0.55)",
    fontSize: 7,
    fontWeight: "800",
    letterSpacing: 3.2,
  },
  neoSubCompact: {
    fontSize: 6,
    letterSpacing: 2.8,
  },
  neoStatusBlock: {
    alignItems: "center",
    gap: 4,
    maxWidth: "100%",
  },
  neoStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.12)",
    backgroundColor: "rgba(2, 6, 23, 0.42)",
  },
  neoStatusDetail: {
    color: "#7dd3fc",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.04,
    maxWidth: 180,
    textAlign: "center",
  },
  neoStatusRowPressed: {
    opacity: 0.88,
  },
  neoConnDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#475569",
  },
  neoConnDotOnline: {
    backgroundColor: "#34d399",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
  },
  neoConnDotOffline: {
    backgroundColor: "#f87171",
    shadowColor: "#f87171",
    shadowOpacity: 0.7,
    shadowRadius: 6,
  },
  neoConnDotConnecting: {
    backgroundColor: "#22d3ee",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.7,
    shadowRadius: 6,
  },
  neoConnLabel: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.8,
  },
  neoBuildStamp: {
    color: "#64748b",
    fontSize: 8,
    fontWeight: "800",
  },
  neoIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  neoIconBtnInner: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(17, 24, 39, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 2,
  },
  neoIconBtnInnerLive: {
    borderColor: "rgba(52, 211, 153, 0.32)",
    backgroundColor: "rgba(8, 32, 28, 0.92)",
  },
  neoIconBtnPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.94 }],
  },
  neoIconBtnDisabled: {
    opacity: 0.38,
  },

  micPanel: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 4,
  },
  micPanelWrap: {
    alignItems: "center",
    gap: 6,
  },
  micPanelFrame: {
    alignSelf: "stretch",
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.1)",
    backgroundColor: "rgba(2, 6, 23, 0.22)",
    overflow: "hidden",
    position: "relative",
  },
  micPanelFrameArmed: {
    borderColor: "rgba(103, 232, 249, 0.22)",
    backgroundColor: "rgba(8, 18, 32, 0.35)",
  },
  micPanelFrameListening: {
    borderColor: "rgba(52, 211, 153, 0.38)",
    backgroundColor: "rgba(6, 44, 38, 0.28)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 3,
  },
  micPanelFrameBridging: {
    borderColor: "rgba(216, 180, 254, 0.42)",
    backgroundColor: "rgba(36, 20, 56, 0.32)",
    shadowColor: "#d8b4fe",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 3,
  },
  micPanelFrameShine: {
    position: "absolute",
    top: 0,
    left: 16,
    right: 16,
    height: 1,
    zIndex: 1,
  },
  micPanelPulse: {
    position: "absolute",
    top: 2,
    left: 2,
    right: 2,
    bottom: 2,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.5)",
    zIndex: 0,
  },
  micOrbPressable: {
    alignItems: "center",
    justifyContent: "center",
  },
  micOrb: {
    width: 196,
    height: 196,
    borderRadius: 98,
  },
  micOrbCompact: {
    width: 164,
    height: 164,
    borderRadius: 82,
  },
  micOrbTiny: {
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  micOrbHalo: {
    position: "absolute",
    backgroundColor: "rgba(45, 212, 191, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  micOrbEnergyRim: {
    position: "absolute",
    margin: -10,
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.38)",
    backgroundColor: "transparent",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 4,
  },
  micOrbOuterRing: {
    position: "absolute",
    margin: -18,
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.14)",
    backgroundColor: "transparent",
  },
  micCosmicRingOuter: {
    position: "absolute",
    margin: -28,
    borderWidth: 1.5,
    borderColor: "rgba(103, 232, 249, 0.22)",
    borderTopColor: "rgba(240, 171, 252, 0.55)",
    borderRightColor: "rgba(103, 232, 249, 0.45)",
    backgroundColor: "transparent",
  },
  micCosmicRingInner: {
    position: "absolute",
    margin: -22,
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.16)",
    borderBottomColor: "rgba(103, 232, 249, 0.42)",
    borderLeftColor: "rgba(52, 211, 153, 0.38)",
    backgroundColor: "transparent",
  },
  micCosmicRingOuterBridge: {
    borderColor: "rgba(216, 180, 254, 0.28)",
    borderTopColor: "rgba(251, 191, 36, 0.55)",
    borderRightColor: "rgba(167, 243, 208, 0.42)",
  },
  micCosmicRingInnerBridge: {
    borderColor: "rgba(216, 180, 254, 0.2)",
    borderBottomColor: "rgba(45, 212, 191, 0.45)",
    borderLeftColor: "rgba(251, 191, 36, 0.35)",
  },
  micOrbRing: {
    position: "absolute",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.38)",
    backgroundColor: "rgba(5, 7, 17, 0.35)",
  },
  micOrbRingLive: {
    borderColor: "rgba(167, 243, 208, 0.68)",
  },
  micOrbSpin: {
    position: "absolute",
    margin: -14,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.12)",
    borderTopColor: "#f8fafc",
    backgroundColor: "transparent",
  },
  micOrbGrille: {
    position: "absolute",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    backgroundColor: "rgba(2, 3, 8, 0.82)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  micOrbGrilleBar: {
    width: 4,
    height: "62%",
    borderRadius: 2,
    backgroundColor: "rgba(16, 24, 39, 0.95)",
  },
  micOrbGrilleBarLive: {
    backgroundColor: "rgba(45, 212, 191, 0.55)",
  },
  micOrbWaveLines: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  micOrbWaveLine: {
    position: "absolute",
    width: "62%",
    height: 1,
    borderRadius: 999,
    backgroundColor: "rgba(148, 163, 184, 0.22)",
  },
  micOrbWaveLineLower: {
    marginTop: 10,
    width: "48%",
    opacity: 0.7,
  },
  micOrbWaveLineLive: {
    backgroundColor: "rgba(103, 232, 249, 0.55)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  micOrbCore: {
    width: 118,
    height: 118,
    borderRadius: 59,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "rgba(31, 41, 55, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 18,
    elevation: 8,
  },
  micOrbCoreCompact: {
    width: 96,
    height: 96,
    borderRadius: 48,
  },
  micOrbCoreTiny: {
    width: 84,
    height: 84,
    borderRadius: 42,
  },
  micOrbRecLed: {
    position: "absolute",
    top: 18,
    right: 22,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#ef4444",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.85)",
    shadowColor: "#ef4444",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 8,
  },
  micOrbOffline: {
    borderWidth: 2,
    borderColor: "rgba(251, 191, 36, 0.72)",
    backgroundColor: "rgba(42, 29, 8, 0.92)",
  },
  micOrbArmed: {
    borderWidth: 2,
    borderColor: "rgba(125, 211, 252, 0.72)",
  },
  micOrbListening: {
    borderWidth: 2,
    borderColor: "rgba(52, 211, 153, 0.78)",
    backgroundColor: "rgba(6, 46, 42, 0.92)",
    shadowColor: "#34d399",
    shadowOpacity: 0.45,
    shadowRadius: 24,
  },
  micOrbSpeaking: {
    borderWidth: 2,
    borderColor: "rgba(216, 180, 254, 0.72)",
    backgroundColor: "rgba(40, 22, 58, 0.92)",
    shadowColor: "#d8b4fe",
    shadowOpacity: 0.42,
    shadowRadius: 22,
  },
  micOrbBusy: {
    opacity: 0.88,
  },
  micOrbPressed: {
    transform: [{ scale: 0.965 }],
  },
  micOrbDisabled: {
    opacity: 0.52,
  },
  micOrbLabel: {
    marginTop: 8,
    color: "#67e8f9",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.4,
    textShadowColor: "rgba(34, 211, 238, 0.35)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  micOrbLabelLive: {
    color: "#a7f3d0",
    textShadowColor: "rgba(52, 211, 153, 0.4)",
  },
  micOrbHintPill: {
    marginTop: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.18)",
    backgroundColor: "rgba(2, 6, 23, 0.42)",
    maxWidth: 300,
  },
  micOrbHint: {
    flex: 1,
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 15,
  },
  micOrbHintLive: {
    color: "#a7f3d0",
  },
  speakingLaneGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 20,
    backgroundColor: "#fbbf24",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.35)",
  },

  liveStatusPanel: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.32)",
    backgroundColor: "rgba(6, 44, 38, 0.55)",
  },
  liveStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#34d399",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    elevation: 2,
  },
  liveStatusText: {
    color: "#34d399",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.2,
  },
  liveStatusPanelSpeaking: {
    borderColor: "rgba(216, 180, 254, 0.35)",
    backgroundColor: "rgba(40, 22, 58, 0.62)",
  },
  liveStatusPanelTranslating: {
    borderColor: "rgba(251, 191, 36, 0.32)",
    backgroundColor: "rgba(42, 28, 8, 0.62)",
  },
  liveStatusPanelArmed: {
    borderColor: "rgba(103, 232, 249, 0.28)",
    backgroundColor: "rgba(12, 24, 42, 0.62)",
  },
  liveStatusTextSpeaking: {
    color: "#d8b4fe",
  },
  liveStatusTextTranslating: {
    color: "#fbbf24",
  },

  laneAccent: {
    width: 3,
    alignSelf: "stretch",
    marginVertical: 14,
    marginLeft: 0,
    borderTopRightRadius: 3,
    borderBottomRightRadius: 3,
    backgroundColor: "rgba(148, 163, 184, 0.35)",
  },
  laneAccentSourceLive: {
    backgroundColor: "#93c5fd",
  },
  laneAccentTargetLive: {
    backgroundColor: "#2dd4bf",
  },
  laneBody: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    position: "relative",
  },
  laneSheen: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    opacity: 0.9,
  },
  laneCopyDock: {
    position: "absolute",
    right: 10,
    bottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    padding: 4,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.55)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
  },
  laneBodyCompact: {
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  laneBodyWithActions: {
    paddingRight: 88,
    paddingBottom: 14,
  },
  speechWorkspace: {
    gap: 8,
  },

  volumeControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 96,
  },
  volumeControlCompact: {
    minWidth: 84,
    gap: 4,
  },
  volumeControlWide: {
    width: "100%",
    minWidth: 0,
    gap: 10,
  },
  volumeToggle: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  volumeTogglePressed: {
    backgroundColor: "rgba(255, 255, 255, 0.07)",
  },
  volumeTrack: {
    width: 72,
    height: 18,
    justifyContent: "center",
    position: "relative",
  },
  volumeTrackWide: {
    flex: 1,
    width: undefined,
    minWidth: 120,
    height: 22,
  },
  volumeTrackBase: {
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(51, 65, 85, 0.5)",
  },
  volumeTrackFill: {
    position: "absolute",
    left: 0,
    height: 3,
    borderRadius: 999,
    backgroundColor: "rgba(45, 212, 191, 0.7)",
  },
  volumeTrackFillHot: {
    backgroundColor: "#2dd4bf",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 6,
    elevation: 2,
  },
  volumeThumb: {
    position: "absolute",
    width: 12,
    height: 12,
    marginLeft: -6,
    marginTop: -4.5,
    borderRadius: 6,
    backgroundColor: "#2dd4bf",
    borderWidth: 2,
    borderColor: "rgba(2, 6, 23, 0.8)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
  },
  volumeThumbLive: {
    backgroundColor: "#5eead4",
    borderColor: "rgba(45, 212, 191, 0.55)",
    shadowOpacity: 0.75,
    shadowRadius: 10,
    elevation: 3,
  },
  speedControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 96,
  },
  speedControlWide: {
    width: "100%",
    minWidth: 0,
  },
  speedControlLabel: {
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: "900",
    minWidth: 36,
    textAlign: "right",
  },
  speedTrack: {
    width: 72,
    height: 22,
    justifyContent: "center",
    position: "relative",
  },
  speedTrackWide: {
    flex: 1,
    width: undefined,
    minWidth: 120,
  },
  speedTrackBase: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(148, 163, 184, 0.22)",
  },
  speedTrackFill: {
    position: "absolute",
    left: 0,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#67e8f9",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
  },
  speedThumb: {
    position: "absolute",
    width: 14,
    height: 14,
    marginLeft: -7,
    borderRadius: 7,
    backgroundColor: "#a5f3fc",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.55)",
    top: 4,
  },

  quickActionsWrap: {
    padding: 4,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.28)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.08)",
  },
  quickActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  quickActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.36)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
  },
  quickActionBtnActive: {
    backgroundColor: "rgba(45, 212, 191, 0.14)",
    borderColor: "rgba(45, 212, 191, 0.4)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 2,
  },
  quickActionBtnDanger: {
    borderColor: "rgba(248, 113, 113, 0.22)",
  },
  quickActionBtnDisabled: {
    opacity: 0.38,
  },
  quickActionBtnPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.9,
  },
  quickActionText: {
    color: "rgba(203, 213, 225, 0.82)",
    fontSize: 11,
    fontWeight: "700",
  },
  quickActionTextActive: {
    color: "#a7f3d0",
  },
  quickActionTextDanger: {
    color: "#fca5a5",
  },

  laneLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  laneLabelFlag: {
    fontSize: 12,
  },

  voiceMeter: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 4,
    height: 22,
    marginTop: 2,
  },
  voiceMeterMuted: {
    opacity: 0.35,
  },
  voiceMeterIdle: {
    opacity: 0.55,
  },
  voiceMeterBar: {
    width: 4,
    height: 18,
    borderRadius: 999,
    backgroundColor: "rgba(51, 65, 85, 0.65)",
  },
  voiceMeterBarActive: {
    backgroundColor: "#5eead4",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 6,
    elevation: 2,
  },

  processingPill: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.28)",
    backgroundColor: "rgba(42, 28, 8, 0.72)",
    overflow: "hidden",
    position: "relative",
    shadowColor: "#fbbf24",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  processingPillGlow: {
    position: "absolute",
    top: -6,
    left: -6,
    right: -6,
    bottom: -6,
    borderRadius: 999,
    backgroundColor: "#fbbf24",
  },
  processingPillIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(251, 191, 36, 0.22)",
  },
  processingPillText: {
    color: "#fde68a",
    fontSize: 11,
    fontWeight: "800",
  },

  emptyState: {
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: "rgba(148, 163, 184, 0.18)",
    backgroundColor: "rgba(12, 18, 38, 0.35)",
    gap: 8,
  },
  emptyStateOffline: {
    borderColor: "rgba(103, 232, 249, 0.22)",
    backgroundColor: "rgba(8, 18, 32, 0.55)",
  },
  emptyStateIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(45, 212, 191, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.24)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 3,
  },
  emptyStateIconOffline: {
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderColor: "rgba(103, 232, 249, 0.28)",
    shadowColor: "#22d3ee",
  },
  emptyStateTitle: {
    color: "#e2e8f0",
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  emptyStateDescription: {
    color: "rgba(148, 163, 184, 0.82)",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 17,
    maxWidth: 280,
  },
  emptyStateTips: {
    marginTop: 4,
    gap: 6,
    alignSelf: "stretch",
  },
  emptyStateCta: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: "#22d3ee",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.45)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 4,
  },
  emptyStateCtaPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.92,
  },
  emptyStateCtaText: {
    color: "#07131f",
    fontSize: 13,
    fontWeight: "900",
  },
  emptyStateTip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  emptyStateTipText: {
    flex: 1,
    color: "rgba(100, 116, 139, 0.9)",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 15,
  },

  routeModeStripWrap: {
    gap: 6,
    paddingVertical: 2,
    position: "relative",
    overflow: "hidden",
  },
  routeModeStripShine: {
    position: "absolute",
    top: 0,
    left: 12,
    right: 12,
    height: 1,
    zIndex: 1,
  },
  routeModeStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 8,
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: "rgba(2, 6, 23, 0.28)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.08)",
  },
  routeModeSpeakerPill: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.22)",
  },
  routeModeText: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  routeModeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    backgroundColor: "rgba(2, 6, 23, 0.36)",
  },
  routeModeChipActive: {
    borderColor: "rgba(45, 212, 191, 0.4)",
    backgroundColor: "rgba(45, 212, 191, 0.14)",
  },
  routeModeChipDisabled: {
    opacity: 0.45,
    borderColor: "rgba(148, 163, 184, 0.12)",
    backgroundColor: "rgba(15, 23, 42, 0.55)",
  },
  routeModeChipPressed: {
    transform: [{ scale: 0.97 }],
    opacity: 0.9,
  },
  routeModeChipText: {
    color: "#94a3b8",
    fontSize: 10,
    fontWeight: "800",
  },
  routeModeChipTextActive: {
    color: "#a7f3d0",
  },
  routeModeSpeaker: {
    color: "#a5f3fc",
    fontSize: 10,
    fontWeight: "800",
  },

  duplexPanel: {
    marginTop: 6,
    marginBottom: 4,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "rgba(12, 18, 38, 0.62)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.22)",
    gap: 8,
  },
  duplexPanelCompact: {
    padding: 8,
    gap: 6,
  },
  duplexPanelHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  duplexPanelTitleWrap: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  duplexPanelTitle: {
    color: "#cbd5e1",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.08,
    textTransform: "uppercase",
  },
  duplexPanelSubtitle: {
    color: "#64748b",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.04,
  },
  duplexPanelMeta: {
    color: "#67e8f9",
    fontSize: 10,
    fontWeight: "800",
  },
  duplexPersonRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  duplexBridge: {
    alignSelf: "center",
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(103, 232, 249, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.22)",
  },
  duplexBridgeActive: {
    borderColor: "rgba(45, 212, 191, 0.55)",
  },
  duplexPersonLane: {
    flex: 1,
    padding: 8,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.55)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    gap: 4,
    position: "relative",
    overflow: "hidden",
  },
  duplexPersonLaneCompact: {
    padding: 6,
  },
  duplexPersonLaneActive: {
    borderColor: "rgba(45, 212, 191, 0.45)",
    backgroundColor: "rgba(6, 44, 38, 0.55)",
  },
  duplexPersonGlow: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(45, 212, 191, 0.12)",
  },
  duplexPersonHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  duplexPersonLabel: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "800",
  },
  duplexPersonLabelActive: {
    color: "#a7f3d0",
  },
  duplexPersonLang: {
    color: "#64748b",
    fontSize: 10,
    fontWeight: "700",
  },
  duplexPersonLiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  duplexPersonLiveDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#34d399",
  },
  duplexPersonLiveText: {
    color: "#6ee7b7",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.06,
    textTransform: "uppercase",
  },

  transcriptStackHeaderWrap: {
    gap: 6,
    marginBottom: 2,
  },
  transcriptStackHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 2,
  },
  transcriptStackHeaderIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.22)",
  },
  transcriptStackHeaderText: {
    flex: 1,
    color: "rgba(148, 163, 184, 0.72)",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  transcriptStackSubtext: {
    color: "#64748b",
    fontSize: 10,
    fontWeight: "700",
    marginLeft: "auto",
    marginRight: 6,
  },
  transcriptStackBadge: {
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(45, 212, 191, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.32)",
  },
  transcriptStackBadgeText: {
    color: "#a7f3d0",
    fontSize: 10,
    fontWeight: "900",
  },
  transcriptStackHeaderLine: {
    height: 1,
    marginHorizontal: 2,
    backgroundColor: "rgba(103, 232, 249, 0.16)",
    borderRadius: 1,
  },

  floatingMicFabWrap: {
    position: "absolute",
    right: 18,
    bottom: 118,
    zIndex: 40,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  floatingMicFabHalo: {
    position: "absolute",
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(52, 211, 153, 0.18)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.35)",
  },
  floatingMicFab: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(31, 41, 55, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.38)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  floatingMicFabArmed: {
    borderColor: "rgba(125, 211, 252, 0.62)",
    backgroundColor: "rgba(15, 35, 55, 0.96)",
  },
  floatingMicFabListening: {
    borderColor: "rgba(52, 211, 153, 0.78)",
    backgroundColor: "rgba(6, 46, 42, 0.96)",
    shadowColor: "#34d399",
    shadowOpacity: 0.42,
  },
  floatingMicFabDisabled: {
    opacity: 0.5,
  },
  floatingMicFabPressed: {
    transform: [{ scale: 0.94 }],
  },
  floatingMicFabRing: {
    position: "absolute",
    top: 4,
    left: 4,
    right: 4,
    bottom: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.16)",
  },
  floatingMicFabRingLive: {
    borderColor: "rgba(45, 212, 191, 0.45)",
  },
  floatingMicFabLed: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ef4444",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.65)",
  },
  floatingMicFabLabel: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(8, 14, 30, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  floatingMicFabLabelLive: {
    borderColor: "rgba(52, 211, 153, 0.45)",
    backgroundColor: "rgba(6, 44, 38, 0.92)",
  },
  floatingMicFabLabelArmed: {
    borderColor: "rgba(125, 211, 252, 0.42)",
  },
  floatingMicFabLabelText: {
    color: "#cbd5e1",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.06,
  },
});
