import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050711",
  },
  page: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: "center",
    backgroundColor: "#050711",
  },
  pageCompact: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  interpreterPanel: {
    flex: 1,
    width: "100%",
    maxHeight: 780,
    alignSelf: "center",
    borderRadius: 28,
    padding: 16,
    backgroundColor: "#0a0f1d",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.28,
    shadowRadius: 32,
    elevation: 14,
    gap: 12,
  },
  interpreterPanelCompact: {
    borderRadius: 22,
    padding: 12,
    gap: 8,
  },
  interpreterPanelTiny: {
    padding: 10,
    gap: 6,
  },
  interpreterPanelOnline: {
    borderColor: "rgba(52, 211, 153, 0.38)",
    shadowColor: "#34d399",
    shadowOpacity: 0.22,
  },
  topBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  topBarCompact: {
    minHeight: 42,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  brand: {
    color: "#f8fafc",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
  },
  brandAccent: {
    color: "#67e8f9",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: 0,
    textShadowColor: "rgba(34, 211, 238, 0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  brandSubline: {
    color: "#9fb6d8",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0,
    textTransform: "uppercase",
  },
  connectionBadge: {
    minWidth: 104,
    maxWidth: 140,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
  },
  connectionBadgePulsing: {
    shadowColor: "#34d399",
    shadowOpacity: 0.2,
  },
  connectionBadgeOnline: {
    borderColor: "rgba(52, 211, 153, 0.42)",
    backgroundColor: "rgba(6, 44, 38, 0.92)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  connectionBadgeOffline: {
    borderColor: "rgba(248, 113, 113, 0.32)",
    backgroundColor: "rgba(31, 18, 21, 0.92)",
    shadowColor: "#f87171",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 2,
  },
  connectionDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  connectionText: {
    flexShrink: 1,
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
  },
  routeBand: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 10,
    padding: 4,
    borderRadius: 22,
    backgroundColor: "rgba(2, 6, 23, 0.35)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.08)",
  },
  routeBandCompact: {
    minHeight: 58,
    gap: 8,
  },
  routeSide: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: "rgba(18, 26, 45, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(96, 165, 250, 0.28)",
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  routeSideActive: {
    backgroundColor: "rgba(15, 45, 43, 0.95)",
    borderColor: "rgba(45, 212, 191, 0.62)",
    shadowColor: "#2dd4bf",
    shadowOpacity: 0.22,
  },
  routeSideCompact: {
    paddingHorizontal: 10,
    borderRadius: 15,
  },
  routeSidePressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.94,
  },
  routeCenter: {
    width: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 21,
    backgroundColor: "#67e8f9",
    alignSelf: "center",
    aspectRatio: 1,
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  routeCenterDisabled: {
    opacity: 0.42,
  },
  routeCenterPressed: {
    transform: [{ scale: 0.94 }],
  },
  routeCaption: {
    color: "#91a6c9",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  routeLanguage: {
    marginTop: 5,
    color: "#f8fafc",
    fontSize: 21,
    fontWeight: "900",
    letterSpacing: 0,
  },
  routeLanguageActive: {
    color: "#a5f3fc",
    textShadowColor: "rgba(34, 211, 238, 0.35)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  voiceButton: {
    width: 164,
    height: 164,
    borderRadius: 82,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#182033",
    borderWidth: 2,
    borderColor: "rgba(125, 211, 252, 0.42)",
    shadowColor: "#38bdf8",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 26,
    elevation: 12,
  },
  voiceButtonCompact: {
    width: 132,
    height: 132,
    borderRadius: 66,
  },
  voiceButtonTiny: {
    width: 116,
    height: 116,
    borderRadius: 58,
  },
  voiceButtonListening: {
    backgroundColor: "#062e2a",
    borderColor: "rgba(52, 211, 153, 0.78)",
    shadowColor: "#34d399",
    shadowOpacity: 0.45,
  },
  voiceButtonArmed: {
    borderColor: "rgba(125, 211, 252, 0.72)",
    shadowOpacity: 0.38,
  },
  voiceButtonSpeaking: {
    backgroundColor: "#28163a",
    borderColor: "rgba(216, 180, 254, 0.7)",
    shadowColor: "#d8b4fe",
    shadowOpacity: 0.42,
  },
  voiceButtonPressed: {
    transform: [{ scale: 0.97 }],
  },
  voiceButtonDisabled: {
    opacity: 0.52,
    borderColor: "rgba(148, 163, 184, 0.28)",
    shadowOpacity: 0.08,
  },
  voiceCore: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(5, 7, 17, 0.78)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    gap: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.32,
    shadowRadius: 10,
    elevation: 4,
  },
  voiceCoreCompact: {
    width: 98,
    height: 98,
    borderRadius: 49,
    gap: 6,
  },
  voiceCoreTiny: {
    width: 86,
    height: 86,
    borderRadius: 43,
    gap: 4,
  },
  voiceButtonText: {
    width: 92,
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 0,
  },
  flowRail: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  flowRailCompact: {
    minHeight: 31,
    gap: 6,
  },
  flowStep: {
    flex: 1,
    minHeight: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: "rgba(17, 24, 39, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    opacity: 0.82,
  },
  flowStepActive: {
    backgroundColor: "rgba(20, 184, 166, 0.32)",
    borderColor: "rgba(45, 212, 191, 0.62)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 5,
    transform: [{ scale: 1.02 }],
    opacity: 1,
  },
  flowStepText: {
    color: "#c7d2fe",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  flowStepTextActive: {
    color: "#ecfdf5",
  },
  transcriptStack: {
    flex: 1,
    minHeight: 180,
    gap: 10,
  },
  transcriptStackCompact: {
    minHeight: 142,
    gap: 8,
  },
  transcriptStackTiny: {
    minHeight: 124,
    gap: 6,
  },
  transcriptLane: {
    flex: 1,
    minHeight: 82,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "rgba(17, 24, 39, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(129, 140, 248, 0.32)",
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 3,
  },
  transcriptLaneCompact: {
    minHeight: 64,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 15,
  },
  transcriptLaneLive: {
    borderColor: "rgba(96, 165, 250, 0.55)",
    shadowColor: "#3b82f6",
    shadowOpacity: 0.22,
    shadowRadius: 18,
  },
  translationLane: {
    flex: 1.12,
    minHeight: 98,
    justifyContent: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: "rgba(6, 31, 28, 0.94)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.38)",
    shadowColor: "#14b8a6",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 4,
  },
  translationLaneCompact: {
    minHeight: 74,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 15,
  },
  translationLaneLive: {
    borderColor: "rgba(45, 212, 191, 0.62)",
    shadowColor: "#14b8a6",
    shadowOpacity: 0.28,
    shadowRadius: 20,
  },
  translationLaneBusy: {
    borderColor: "rgba(251, 191, 36, 0.45)",
    backgroundColor: "rgba(40, 28, 8, 0.92)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.22,
    shadowRadius: 14,
  },
  turnRail: {
    minHeight: 34,
    flexDirection: "row",
    gap: 8,
    marginTop: 2,
  },
  turnChip: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "rgba(16, 24, 39, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  turnChipActive: {
    borderColor: "rgba(103, 232, 249, 0.42)",
    backgroundColor: "rgba(8, 47, 73, 0.72)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.16,
    shadowRadius: 8,
  },
  turnChipWarning: {
    backgroundColor: "#281d0b",
    borderColor: "rgba(245, 158, 11, 0.45)",
    shadowColor: "#fbbf24",
    shadowOpacity: 0.12,
  },
  turnChipText: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  turnChipSpeaker: {
    color: "#67e8f9",
    fontWeight: "900",
  },
  laneLabel: {
    color: "#93a4bd",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  laneLabelFlex: {
    flex: 1,
    minWidth: 0,
  },
  topBarBrand: {
    flex: 1,
    minWidth: 0,
  },
  laneLabelLive: {
    color: "#67e8f9",
    textShadowColor: "rgba(34, 211, 238, 0.35)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  laneText: {
    marginTop: 7,
    color: "#f1f5f9",
    fontSize: 21,
    lineHeight: 26,
    fontWeight: "800",
  },
  translationText: {
    marginTop: 7,
    color: "#bbf7d0",
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "900",
  },
  lanePlaceholder: {
    color: "#64748b",
    fontStyle: "italic",
    fontWeight: "600",
  },
  statusStrip: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 13,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.16)",
  },
  statusStripCompact: {
    minHeight: 42,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  statusStripPressed: {
    backgroundColor: "rgba(30, 41, 59, 0.95)",
    borderColor: "rgba(103, 232, 249, 0.32)",
  },
  statusStripOnline: {
    backgroundColor: "rgba(6, 31, 28, 0.88)",
    borderColor: "rgba(52, 211, 153, 0.28)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  statusTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  statusLine: {
    fontSize: 13,
    fontWeight: "900",
  },
  statusDetail: {
    marginTop: 2,
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "700",
  },
  controlDock: {
    minHeight: 62,
    flexDirection: "row",
    alignItems: "stretch",
    gap: 7,
    padding: 4,
    borderRadius: 20,
    backgroundColor: "rgba(2, 6, 23, 0.35)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.08)",
  },
  controlDockCompact: {
    minHeight: 56,
    gap: 5,
  },
  iconControl: {
    flex: 1,
    minHeight: 56,
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingHorizontal: 6,
    borderRadius: 16,
    backgroundColor: "rgba(18, 24, 38, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.22)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 3,
  },
  iconControlActive: {
    backgroundColor: "rgba(20, 184, 166, 0.32)",
    borderColor: "rgba(45, 212, 191, 0.55)",
    shadowColor: "#2dd4bf",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  iconControlDanger: {
    backgroundColor: "#24131b",
    borderColor: "rgba(251, 113, 133, 0.38)",
    shadowColor: "#fb7185",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  iconControlDisabled: {
    opacity: 0.42,
  },
  iconControlPressed: {
    transform: [{ scale: 0.97 }],
    borderColor: "rgba(103, 232, 249, 0.35)",
    backgroundColor: "rgba(30, 41, 59, 0.95)",
  },
  iconControlText: {
    color: "#dbeafe",
    fontSize: 10,
    fontWeight: "900",
    textAlign: "center",
  },
  iconControlTextActive: {
    color: "#07131f",
  },

  actionButton: {
    flex: 1,
    minHeight: 46,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "transparent",
  },
  actionButton_primary: {
    backgroundColor: "#0891b2",
    borderColor: "rgba(103, 232, 249, 0.38)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButton_success: {
    backgroundColor: "#059669",
    borderColor: "rgba(167, 243, 208, 0.38)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButton_danger: {
    backgroundColor: "#dc2626",
    borderColor: "rgba(254, 202, 202, 0.28)",
    shadowColor: "#f87171",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  actionButton_ghost: { backgroundColor: "rgba(15, 23, 42, 0.7)", borderColor: "rgba(148, 163, 184, 0.22)" },
  actionButtonDisabled: { opacity: 0.45 },
  actionButtonPressed: { transform: [{ scale: 0.98 }] },
  actionButtonText: { color: "#f8fafc", fontSize: 14, fontWeight: "900", textAlign: "center" },
  actionButtonTextGhost: { color: "#cbd5e1" },
  smallAction: { flex: 0, minHeight: 34, paddingHorizontal: 12 },

  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(17, 24, 39, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  settingsBtnPressed: {
    backgroundColor: "rgba(30, 41, 59, 0.95)",
    borderColor: "rgba(103, 232, 249, 0.32)",
    transform: [{ scale: 0.96 }],
  },
  topBarActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  scrollPanel: {
    flex: 1,
    minHeight: 120,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.12)",
    backgroundColor: "rgba(2, 6, 23, 0.42)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
    overflow: "hidden",
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 12,
  },
  banner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
  },
  bannerIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  bannerIconError: {
    backgroundColor: "rgba(248, 113, 113, 0.1)",
    borderColor: "rgba(248, 113, 113, 0.28)",
  },
  bannerIconWarning: {
    backgroundColor: "rgba(251, 191, 36, 0.1)",
    borderColor: "rgba(251, 191, 36, 0.28)",
  },
  bannerError: {
    backgroundColor: "rgba(31, 18, 21, 0.96)",
    borderColor: "rgba(248, 113, 113, 0.45)",
    shadowColor: "#f87171",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  bannerWarning: {
    backgroundColor: "rgba(40, 29, 11, 0.96)",
    borderColor: "rgba(245, 158, 11, 0.45)",
    shadowColor: "#fbbf24",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  bannerText: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  bannerAction: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.16)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.35)",
  },
  bannerActionText: {
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: "900",
  },
  bannerActionPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.97 }],
  },
  bannerDismissPressed: {
    opacity: 0.65,
    transform: [{ scale: 0.92 }],
  },
  settingsOverlay: {
    flex: 1,
    backgroundColor: "#050711",
  },
  settingsScroll: {
    flex: 1,
    backgroundColor: "#050711",
  },
  hintStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "rgba(12, 20, 38, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.2)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  hintStripIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.12)",
  },
  hintStripText: {
    flex: 1,
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  loadingScreen: {
    flex: 1,
    backgroundColor: "#050711",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    paddingHorizontal: 24,
  },
  loadingBrandWrap: {
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  loadingIconRing: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.35)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 18,
    elevation: 6,
  },
  loadingIconGlyph: {
    fontSize: 32,
  },
  loadingBrandRow: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  loadingBrandMark: {
    color: "#f8fafc",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: 4,
  },
  loadingBrandAccent: {
    color: "#67e8f9",
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: 4,
    textShadowColor: "rgba(34, 211, 238, 0.4)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  loadingBrandSub: {
    color: "#67e8f9",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 4,
  },
  loadingScreenText: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    lineHeight: 20,
    maxWidth: 280,
    letterSpacing: 0.2,
  },
  voiceButtonWrap: {
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  stopListeningBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.4)",
    backgroundColor: "rgba(127, 29, 29, 0.28)",
  },
  stopListeningBtnPressed: {
    opacity: 0.85,
  },
  stopListeningText: {
    color: "#fecaca",
    fontSize: 13,
    fontWeight: "800",
  },
  voicePulseRing: {
    position: "absolute",
    width: 196,
    height: 196,
    borderRadius: 98,
    borderWidth: 2,
    borderColor: "rgba(52, 211, 153, 0.45)",
    backgroundColor: "rgba(52, 211, 153, 0.06)",
    shadowColor: "#34d399",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 6,
  },
  voicePulseRingCompact: {
    width: 160,
    height: 160,
    borderRadius: 80,
  },
  voicePulseRingTiny: {
    width: 140,
    height: 140,
    borderRadius: 70,
  },
  offlineCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: "rgba(12, 26, 46, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(34, 211, 238, 0.35)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  offlineCtaIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  offlineCtaText: {
    flex: 1,
    color: "#e0f2fe",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  offlineCtaBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#22d3ee",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.45)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  offlineCtaBtnPressed: {
    transform: [{ scale: 0.97 }],
    opacity: 0.92,
  },
  offlineCtaBtnText: {
    color: "#07131f",
    fontSize: 12,
    fontWeight: "900",
  },
  routeFlag: {
    fontSize: 20,
    marginBottom: 2,
  },
  routeTapHint: {
    marginTop: 4,
    color: "#64748b",
    fontSize: 9,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  voiceButtonBusy: {
    opacity: 0.85,
  },
  toast: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 28,
    zIndex: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.28)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 12,
  },
  toastIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.9)",
    borderWidth: 1,
  },
  toastText: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
  },
  toastSuccess: {
    borderColor: "rgba(52, 211, 153, 0.45)",
    shadowColor: "#34d399",
    shadowOpacity: 0.22,
  },
  toastError: {
    borderColor: "rgba(248, 113, 113, 0.45)",
    shadowColor: "#f87171",
    shadowOpacity: 0.22,
  },
  toastInfo: {
    borderColor: "rgba(103, 232, 249, 0.35)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.15,
  },
  laneHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  laneActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  laneActionBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  laneActionBtnPressed: {
    backgroundColor: "rgba(30, 41, 59, 0.9)",
    borderColor: "rgba(103, 232, 249, 0.28)",
    transform: [{ scale: 0.94 }],
  },
  contextChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(34, 211, 238, 0.28)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  contextChipText: {
    color: "#a5f3fc",
    fontSize: 11,
    fontWeight: "800",
  },
});
