import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050711",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  titleAccent: {
    color: "#67e8f9",
  },
  subtitle: {
    marginTop: 2,
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "700",
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
  },
  closeBtnPressed: {
    backgroundColor: "#1e293b",
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  list: {
    padding: 16,
    gap: 10,
    paddingBottom: 24,
  },
  card: {
    flexDirection: "row",
    gap: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#0a0f1d",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.18)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  cardPressed: {
    backgroundColor: "#0f172a",
    borderColor: "rgba(103, 232, 249, 0.28)",
    transform: [{ scale: 0.99 }],
  },
  tipNumberWrap: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.3)",
    alignSelf: "flex-start",
    marginTop: 2,
  },
  tipNumber: {
    color: "#67e8f9",
    fontSize: 11,
    fontWeight: "900",
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.12)",
  },
  cardBody: {
    flex: 1,
    gap: 4,
  },
  cardTitle: {
    color: "#e2e8f0",
    fontSize: 15,
    fontWeight: "900",
  },
  cardText: {
    color: "#94a3b8",
    fontSize: 13,
    lineHeight: 19,
  },
  doneBtn: {
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: "#22d3ee",
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  doneBtnPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.98 }],
  },
  doneBtnText: {
    color: "#07131f",
    fontSize: 15,
    fontWeight: "900",
  },
});
