import { StyleSheet } from "react-native";

export default StyleSheet.create({
  backdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(2, 6, 23, 0.72)",
  },
  backdropTap: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetWrap: {
    maxHeight: "78%",
  },
  sheet: {
    backgroundColor: "#0a0f1d",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 16,
  },
  handle: {
    alignSelf: "center",
    width: 42,
    height: 4,
    borderRadius: 999,
    marginTop: 10,
    marginBottom: 4,
    backgroundColor: "rgba(103, 232, 249, 0.42)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  title: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "900",
    flex: 1,
  },
  titleAccent: {
    color: "#67e8f9",
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
  },
  closeBtnPressed: {
    backgroundColor: "#1e293b",
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 14,
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.22)",
  },
  searchRowFocused: {
    borderColor: "rgba(103, 232, 249, 0.45)",
    backgroundColor: "#0f172a",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "600",
    padding: 0,
  },
  emptyWrap: {
    alignItems: "center",
    gap: 12,
    paddingVertical: 36,
    paddingHorizontal: 20,
  },
  emptyIconRing: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.22)",
  },
  emptyText: {
    color: "#94a3b8",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  list: {
    paddingHorizontal: 14,
    paddingBottom: 24,
    gap: 6,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.14)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  rowActive: {
    backgroundColor: "#0f2d2b",
    borderColor: "rgba(34, 211, 238, 0.45)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 4,
  },
  rowPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  flag: {
    fontSize: 22,
  },
  label: {
    flex: 1,
    color: "#e2e8f0",
    fontSize: 16,
    fontWeight: "700",
  },
  labelActive: {
    color: "#a5f3fc",
  },
});
