import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#03050a",
  },
  flex: {
    flex: 1,
  },
  scroll: {
    padding: 20,
    paddingBottom: 40,
    gap: 14,
  },
  hero: {
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
    marginTop: 12,
  },
  heroIconHalo: {
    width: 96,
    height: 96,
    alignItems: "center",
    justifyContent: "center",
  },
  heroIconRingPulse: {
    position: "absolute",
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.42)",
    backgroundColor: "rgba(34, 211, 238, 0.06)",
  },
  heroIconRing: {
    width: 84,
    height: 84,
    borderRadius: 42,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.35)",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 8,
  },
  headerShine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    zIndex: 1,
  },
  stepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  stepDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(148, 163, 184, 0.35)",
  },
  stepDotActive: {
    width: 22,
    backgroundColor: "#22d3ee",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  stepDotDone: {
    backgroundColor: "#34d399",
  },
  title: {
    color: "#f8fafc",
    fontSize: 28,
    fontWeight: "900",
    textAlign: "center",
  },
  titleAccent: {
    color: "#67e8f9",
  },
  subtitle: {
    color: "#94a3b8",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    maxWidth: 340,
  },
  card: {
    backgroundColor: "#0a0f1d",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.2)",
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
    overflow: "hidden",
    position: "relative",
  },
  cardShine: {
    position: "absolute",
    top: 0,
    left: 16,
    right: 16,
    height: 1,
  },
  cardActive: {
    borderColor: "rgba(103, 232, 249, 0.42)",
    shadowColor: "#22d3ee",
    shadowOpacity: 0.18,
  },
  cardHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cardTitle: {
    color: "#67e8f9",
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    flex: 1,
  },
  cardIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34, 211, 238, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(103, 232, 249, 0.28)",
  },
  hint: {
    color: "#94a3b8",
    fontSize: 13,
    lineHeight: 19,
  },
  input: {
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.28)",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#f8fafc",
    fontSize: 15,
  },
  inputFocused: {
    borderColor: "rgba(103, 232, 249, 0.55)",
    backgroundColor: "#0f172a",
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 3,
  },
  primaryBtn: {
    backgroundColor: "#22d3ee",
    borderRadius: 999,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 48,
    shadowColor: "#22d3ee",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  continueBtn: {
    marginTop: 8,
  },
  secondaryBtn: {
    backgroundColor: "rgba(20, 184, 166, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.45)",
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryBtnText: {
    color: "#07131f",
    fontSize: 15,
    fontWeight: "900",
  },
  secondaryBtnText: {
    color: "#ccfbf1",
    fontSize: 14,
    fontWeight: "900",
  },
  btnPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.92,
  },
  btnDisabled: {
    opacity: 0.72,
    backgroundColor: "#334155",
    shadowOpacity: 0.08,
  },
  primaryBtnTextDisabled: {
    color: "#94a3b8",
  },
  errorText: {
    color: "#fca5a5",
    fontSize: 13,
    fontWeight: "700",
  },
  successRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(6, 44, 38, 0.72)",
    borderWidth: 1,
    borderColor: "rgba(52, 211, 153, 0.32)",
    alignSelf: "flex-start",
  },
  successText: {
    color: "#6ee7b7",
    fontSize: 13,
    fontWeight: "800",
  },
});
